//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AdministracionEntities : DbContext
    {
        public AdministracionEntities()
            : base("name=AdministracionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLog { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<LogIngresos> LogIngresos { get; set; }
        public virtual DbSet<LogIngrFallidos> LogIngrFallidos { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<ParametrosSistema> ParametrosSistema { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<PerfilMenu> PerfilMenu { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolMenuPermiso> RolMenuPermiso { get; set; }
        public virtual DbSet<RolPerfil> RolPerfil { get; set; }
        public virtual DbSet<TipoNotificacion> TipoNotificacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<UsuarioInfo> ListarUsuarios(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioInfo>("ListarUsuarios", idParameter);
        }
    
        public virtual ObjectResult<OpcionMenuUsuarioInfo> ListarOpcionMenuUsuario(string correo_username)
        {
            var correo_usernameParameter = correo_username != null ?
                new ObjectParameter("correo_username", correo_username) :
                new ObjectParameter("correo_username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionMenuUsuarioInfo>("ListarOpcionMenuUsuario", correo_usernameParameter);
        }
    
        public virtual ObjectResult<RolInfo> ListaRol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RolInfo>("ListaRol");
        }
    
        public virtual ObjectResult<PerfilInfo> ListaPerfil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilInfo>("ListaPerfil");
        }
    
        public virtual ObjectResult<MenuHijosInfo> ListaMenuHijos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuHijosInfo>("ListaMenuHijos");
        }
    
        public virtual ObjectResult<MenuInfo> ListaMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuInfo>("ListaMenu");
        }
    
        public virtual ObjectResult<UsuarioInfo> ListadoUsuarios(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioInfo>("ListadoUsuarios", idParameter);
        }
    
        public virtual ObjectResult<TipoNotificacionesInfo> ListadoTipoNotificaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipoNotificacionesInfo>("ListadoTipoNotificaciones");
        }
    
        public virtual ObjectResult<CatalogoInfo> ListadoSubcatalogos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogoInfo>("ListadoSubcatalogos");
        }
    
        public virtual ObjectResult<PerfilInfo> ListadoRolPerfil(Nullable<int> idrol)
        {
            var idrolParameter = idrol.HasValue ?
                new ObjectParameter("idrol", idrol) :
                new ObjectParameter("idrol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilInfo>("ListadoRolPerfil", idrolParameter);
        }
    
        public virtual ObjectResult<RolInfo> ListadoRol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RolInfo>("ListadoRol");
        }
    
        public virtual ObjectResult<MenuInfo> ListadoPerfilMenu(Nullable<int> idperfil)
        {
            var idperfilParameter = idperfil.HasValue ?
                new ObjectParameter("idperfil", idperfil) :
                new ObjectParameter("idperfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuInfo>("ListadoPerfilMenu", idperfilParameter);
        }
    
        public virtual ObjectResult<PerfilInfo> ListadoPerfil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PerfilInfo>("ListadoPerfil");
        }
    
        public virtual ObjectResult<ParametrosSistemasInfo> ListadoParametrosSistemas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ParametrosSistemasInfo>("ListadoParametrosSistemas");
        }
    
        public virtual ObjectResult<OrdenMenuInfo> ListadoOrdenMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrdenMenuInfo>("ListadoOrdenMenu");
        }
    
        public virtual ObjectResult<MenuInfo> ListadoMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuInfo>("ListadoMenu");
        }
    
        public virtual ObjectResult<CatalogoInfo> ListadoCatalogosPadres()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogoInfo>("ListadoCatalogosPadres");
        }
    
        public virtual ObjectResult<CatalogoInfo> ListadoCatalogo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogoInfo>("ListadoCatalogo");
        }
    
        public virtual ObjectResult<CatalogoInfo> ListaCatalogos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogoInfo>("ListaCatalogos");
        }
    
        public virtual int LimpiarRolMenuPermisosCompleto(Nullable<int> idRol, Nullable<int> idPerfil)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(int));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LimpiarRolMenuPermisosCompleto", idRolParameter, idPerfilParameter);
        }
    
        public virtual int LimpiarRolMenuPermisos(Nullable<int> idRol, Nullable<int> idPerfil, Nullable<int> idMenu)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(int));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("idMenu", idMenu) :
                new ObjectParameter("idMenu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LimpiarRolMenuPermisos", idRolParameter, idPerfilParameter, idMenuParameter);
        }
    
        public virtual int GuardarRolMenuPermisos(Nullable<int> idRol, Nullable<int> idPerfil, Nullable<int> idMenu, Nullable<int> idAccion, Nullable<int> createdBy, Nullable<int> updateBy, Nullable<System.DateTime> createAt, Nullable<System.DateTime> updateAt, Nullable<bool> estado)
        {
            var idRolParameter = idRol.HasValue ?
                new ObjectParameter("idRol", idRol) :
                new ObjectParameter("idRol", typeof(int));
    
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            var idMenuParameter = idMenu.HasValue ?
                new ObjectParameter("idMenu", idMenu) :
                new ObjectParameter("idMenu", typeof(int));
    
            var idAccionParameter = idAccion.HasValue ?
                new ObjectParameter("idAccion", idAccion) :
                new ObjectParameter("idAccion", typeof(int));
    
            var createdByParameter = createdBy.HasValue ?
                new ObjectParameter("createdBy", createdBy) :
                new ObjectParameter("createdBy", typeof(int));
    
            var updateByParameter = updateBy.HasValue ?
                new ObjectParameter("updateBy", updateBy) :
                new ObjectParameter("updateBy", typeof(int));
    
            var createAtParameter = createAt.HasValue ?
                new ObjectParameter("createAt", createAt) :
                new ObjectParameter("createAt", typeof(System.DateTime));
    
            var updateAtParameter = updateAt.HasValue ?
                new ObjectParameter("updateAt", updateAt) :
                new ObjectParameter("updateAt", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarRolMenuPermisos", idRolParameter, idPerfilParameter, idMenuParameter, idAccionParameter, createdByParameter, updateByParameter, createAtParameter, updateAtParameter, estadoParameter);
        }
    
        public virtual int EnviarCorreoUsuarioResetClave(Nullable<int> id_usuario, string clave)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnviarCorreoUsuarioResetClave", id_usuarioParameter, claveParameter);
        }
    
        public virtual int EnviarCorreoUsuarioGenérico(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnviarCorreoUsuarioGenérico", id_usuarioParameter);
        }
    
        public virtual int EnviarCorreoUsuarioCambioClave(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnviarCorreoUsuarioCambioClave", id_usuarioParameter);
        }
    
        public virtual int EnviarCorreoUsuario(Nullable<int> id_usuario, string clave)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EnviarCorreoUsuario", id_usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<UsuarioInfo> ConsultarUsuarioId(string correo_user)
        {
            var correo_userParameter = correo_user != null ?
                new ObjectParameter("correo_user", correo_user) :
                new ObjectParameter("correo_user", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioInfo>("ConsultarUsuarioId", correo_userParameter);
        }
    
        public virtual ObjectResult<UsuarioInfo> ConsultarUsuarioExistente(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioInfo>("ConsultarUsuarioExistente", usuarioParameter);
        }
    
        public virtual ObjectResult<UsuarioInfo> ConsultarUsuarioClave(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioInfo>("ConsultarUsuarioClave", usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<Usuario> ConsultarUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("ConsultarUsuario", idParameter);
        }
    
        public virtual ObjectResult<Usuario> ConsultarUsuario(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("ConsultarUsuario", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<NumeroHijosCatalogoInfo> ConsultarNumeroHijosCatalogo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NumeroHijosCatalogoInfo>("ConsultarNumeroHijosCatalogo", idParameter);
        }
    
        public virtual ObjectResult<CatalogosPorPadreInfo> ConsultarCatalogosPorPadre(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogosPorPadreInfo>("ConsultarCatalogosPorPadre", idParameter);
        }
    
        public virtual ObjectResult<CatalogosPorIdInfo> ConsultarCatalogosPorId(Nullable<int> id, string codigo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogosPorIdInfo>("ConsultarCatalogosPorId", idParameter, codigoParameter);
        }
    
        public virtual ObjectResult<CatalogoInfo> ConsultarCatalogosCodigoIdPadre(string codigo, Nullable<int> id)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogoInfo>("ConsultarCatalogosCodigoIdPadre", codigoParameter, idParameter);
        }
    
        public virtual ObjectResult<CatalogoInfo> ConsultarCatalogoPorCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CatalogoInfo>("ConsultarCatalogoPorCodigo", codigoParameter);
        }
    
        public virtual ObjectResult<Catalogo> ConsultarCatalogo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Catalogo>("ConsultarCatalogo", idParameter);
        }
    
        public virtual ObjectResult<Catalogo> ConsultarCatalogo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Catalogo>("ConsultarCatalogo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<Menu> ConsultarMenu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Menu>("ConsultarMenu", idParameter);
        }
    
        public virtual ObjectResult<Menu> ConsultarMenu(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Menu>("ConsultarMenu", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<ParametrosSistema> ConsultarParametrosSistema(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ParametrosSistema>("ConsultarParametrosSistema", idParameter);
        }
    
        public virtual ObjectResult<ParametrosSistema> ConsultarParametrosSistema(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ParametrosSistema>("ConsultarParametrosSistema", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<Perfil> ConsultarPerfil(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Perfil>("ConsultarPerfil", idParameter);
        }
    
        public virtual ObjectResult<Perfil> ConsultarPerfil(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Perfil>("ConsultarPerfil", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<Rol> ConsultarRol(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rol>("ConsultarRol", idParameter);
        }
    
        public virtual ObjectResult<Rol> ConsultarRol(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rol>("ConsultarRol", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<TipoNotificacion> ConsultarTipoNotificacion(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipoNotificacion>("ConsultarTipoNotificacion", idParameter);
        }
    
        public virtual ObjectResult<TipoNotificacion> ConsultarTipoNotificacion(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TipoNotificacion>("ConsultarTipoNotificacion", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<UsuarioRolMenuPermisoInfo> ListadoRolPerfilMenuPermisos(Nullable<int> id_rol, Nullable<int> id_perfil)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            var id_perfilParameter = id_perfil.HasValue ?
                new ObjectParameter("id_perfil", id_perfil) :
                new ObjectParameter("id_perfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioRolMenuPermisoInfo>("ListadoRolPerfilMenuPermisos", id_rolParameter, id_perfilParameter);
        }
    
        public virtual ObjectResult<UsuarioRolMenuPermisoInfo> ConsultarUsuarioRolMenuPermiso(Nullable<int> id_usuario, string controlador)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var controladorParameter = controlador != null ?
                new ObjectParameter("controlador", controlador) :
                new ObjectParameter("controlador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuarioRolMenuPermisoInfo>("ConsultarUsuarioRolMenuPermiso", id_usuarioParameter, controladorParameter);
        }
    
        public virtual ObjectResult<MenuRutaAccesoInfo> ConsultarMenuRutaAcceso(Nullable<int> id_rol)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MenuRutaAccesoInfo>("ConsultarMenuRutaAcceso", id_rolParameter);
        }
    
        public virtual ObjectResult<string> ConsultarCorreosNotificaciones(Nullable<int> idPerfil)
        {
            var idPerfilParameter = idPerfil.HasValue ?
                new ObjectParameter("idPerfil", idPerfil) :
                new ObjectParameter("idPerfil", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("ConsultarCorreosNotificaciones", idPerfilParameter);
        }
    }
}
