//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionEquipo
    {
        public int IDAsignacionEquipo { get; set; }
        public System.DateTime FechaAsignacionEquipo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public bool Estado { get; set; }
    }
}
