//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        public int IdCatalogo { get; set; }
        public string CodigoCatalogo { get; set; }
        public string NombreCatalogo { get; set; }
        public string DescripcionCatalogo { get; set; }
        public Nullable<int> IdCatalogoPadre { get; set; }
        public Nullable<bool> EstadoCatalogo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    }
}
