//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosRequerimientoEquipo
    {
        public int IDComentariosRequerimientoEquipo { get; set; }
        public string Comentario { get; set; }
        public int RequerimientoEquipoID { get; set; }
        public int UsuarioID { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Estado { get; set; }
    }
}
