//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesvinculacionPersonal
    {
        public int IDDesvinculacionPersonal { get; set; }
        public int Motivo { get; set; }
        public int UsuarioID { get; set; }
        public int UsuarioResponsableID { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public bool SalidaSeguroMedico { get; set; }
        public bool EncuestaSalida { get; set; }
        public bool Estado { get; set; }
    }
}
