//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesvinculacionPersonal
    {
        public int IDDesvinculacionPersonal { get; set; }
        public int Motivo { get; set; }
        public int UsuarioID { get; set; }
        public int UsuarioResponsableID { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public bool SalidaSeguroMedico { get; set; }
        public bool EncuestaSalida { get; set; }
        public bool Estado { get; set; }
    }
}
