//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class DesvinculacionPersonalInfo
    {
        public int IDDesvinculacionPersonal { get; set; }
        public int Motivo { get; set; }
        public string TextoMotivo { get; set; }
        public int UsuarioID { get; set; }
        public string UsuarioDesvinculado { get; set; }
        public int UsuarioResponsableID { get; set; }
        public string UsuarioResponsableDesvinculacion { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public bool SalidaSeguroMedico { get; set; }
        public string TextoEstadoSalidaSeguroMedico { get; set; }
        public bool EncuestaSalida { get; set; }
        public string TextoEstadoEncuestaSalida { get; set; }
        public bool Estado { get; set; }
        public string TextoEstadoDesvinculacionPersonal { get; set; }
        public string IdentificacionUsuario { get; set; }
        public Nullable<int> JefeDirecto { get; set; }
        public string TextoCatalogoJefeDirecto { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Cargo { get; set; }
        public string TextoCatalogoCargo { get; set; }
        public string TextoCatalogoArea { get; set; }
        public Nullable<int> Empresa { get; set; }
        public string TextoCatalogoEmpresa { get; set; }
        public string TelefonoUsuario { get; set; }
        public string CelularUsuario { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string TextoCatalogoCiudadResidencia { get; set; }
    }
}
