//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class DetalleExperienciasInfo
    {
        public int IDDetalleExperiencias { get; set; }
        public string Empresa { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> Cargo { get; set; }
        public string TextoCatalogoCargo { get; set; }
        public int FichaIngresoID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string NombresUsuario { get; set; }
        public string ApellidosUsuario { get; set; }
        public string IdentificacionUsuario { get; set; }
        public Nullable<int> CiudadUsuario { get; set; }
        public string EmailUsuario { get; set; }
        public string TelefonoUsuario { get; set; }
        public string CelularUsuario { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> GeneroUsuario { get; set; }
        public string TextoCatalogoGeneroUsuario { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public string TextoCatalogoNacionalidad { get; set; }
        public Nullable<int> LugarNacimiento { get; set; }
        public string TextoCatalogoLugarNacimiento { get; set; }
        public Nullable<System.DateTime> FechaNacimientoUsuario { get; set; }
        public Nullable<int> CiudadResidencia { get; set; }
        public string TextoCatalogoCiudadResidencia { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public string TextoCatalogoEstadoCivil { get; set; }
        public Nullable<int> Banco { get; set; }
        public string TextoCatalogoBanco { get; set; }
        public string NumeroCuentaBancaria { get; set; }
        public Nullable<int> TipoSangre { get; set; }
        public string TextoCatalogoTipoSangre { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngresoFicha { get; set; }
        public string DireccionCallePrincipal { get; set; }
        public string DireccionCalleSecundaria { get; set; }
        public string DireccionNumeroCasa { get; set; }
        public string DireccionConjuntoResidencial { get; set; }
        public string NombresContactoEmergencia { get; set; }
        public string ApellidosContactoEmergencia { get; set; }
        public Nullable<int> ParentescoContactoEmergencia { get; set; }
        public string TextoCatalogoParentescoContactoEmergencia { get; set; }
        public string TelefonoContactoEmergencia { get; set; }
        public string CelularContactoEmergencia { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public string TextoCatalogoTipoCuenta { get; set; }
    }
}
