//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class DetalleEquiposEntregadosInfo
    {
        public int IDDetalleEquiposEntregados { get; set; }
        public int DesvinculacionPersonalID { get; set; }
        public int EquipoID { get; set; }
        public string NombreEquipo { get; set; }
        public int Entregado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> Motivo { get; set; }
        public string TextoMotivo { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string UsuarioDesvinculado { get; set; }
        public Nullable<int> UsuarioResponsableID { get; set; }
        public string UsuarioResponsableDesvinculacion { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<bool> SalidaSeguroMedico { get; set; }
        public string TextoEstadoSalidaSeguroMedico { get; set; }
        public Nullable<bool> EncuestaSalida { get; set; }
        public string TextoEstadoEncuestaSalida { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string TextoEstadoDesvinculacionPersonal { get; set; }
        public string TextoCatalogoEntregado { get; set; }
        public string Codigo { get; set; }
        public string SerieEquipo { get; set; }
        public Nullable<int> Proveedor { get; set; }
        public string TextoCatalogoProveedor { get; set; }
        public Nullable<decimal> Costo { get; set; }
    }
}
