//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEquiposEntregados
    {
        public int IDDetalleEquiposEntregados { get; set; }
        public int DesvinculacionPersonalID { get; set; }
        public int EquipoID { get; set; }
        public int Entregado { get; set; }
        public string Observaciones { get; set; }
    }
}
