//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCargasFamiliares
    {
        public int IDDetalleCargasFamiliares { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<int> Genero { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public int FichaIngresoID { get; set; }
        public Nullable<int> Parentesco { get; set; }
    }
}
