//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class DetalleEstudiosInfo
    {
        public int IDDetalleEstudios { get; set; }
        public Nullable<int> TipoEstudio { get; set; }
        public string TextoCatalogoTipoEstudio { get; set; }
        public Nullable<int> Institucion { get; set; }
        public string TextoCatalogoInstitucion { get; set; }
        public Nullable<int> Titulo { get; set; }
        public string TextoCatalogoTitulo { get; set; }
        public Nullable<int> AnioFinalizacion { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public string TextoCatalogoCiudad { get; set; }
        public Nullable<int> Pais { get; set; }
        public string TextoCatalogoPais { get; set; }
        public int FichaIngresoID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string NombresUsuario { get; set; }
        public string ApellidosUsuario { get; set; }
        public string IdentificacionUsuario { get; set; }
        public Nullable<int> CiudadUsuario { get; set; }
        public string EmailUsuario { get; set; }
        public string TelefonoUsuario { get; set; }
        public string CelularUsuario { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> GeneroUsuario { get; set; }
        public string TextoCatalogoGeneroUsuario { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public string TextoCatalogoNacionalidad { get; set; }
        public Nullable<int> LugarNacimiento { get; set; }
        public string TextoCatalogoLugarNacimiento { get; set; }
        public Nullable<System.DateTime> FechaNacimientoUsuario { get; set; }
        public Nullable<int> CiudadResidencia { get; set; }
        public string TextoCatalogoCiudadResidencia { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public string TextoCatalogoEstadoCivil { get; set; }
        public Nullable<int> Banco { get; set; }
        public string TextoCatalogoBanco { get; set; }
        public string NumeroCuentaBancaria { get; set; }
        public Nullable<int> TipoSangre { get; set; }
        public string TextoCatalogoTipoSangre { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaIngresoFicha { get; set; }
        public string DireccionCallePrincipal { get; set; }
        public string DireccionCalleSecundaria { get; set; }
        public string DireccionNumeroCasa { get; set; }
        public string DireccionConjuntoResidencial { get; set; }
        public string NombresContactoEmergencia { get; set; }
        public string ApellidosContactoEmergencia { get; set; }
        public Nullable<int> ParentescoContactoEmergencia { get; set; }
        public string TextoCatalogoParentescoContactoEmergencia { get; set; }
        public string TelefonoContactoEmergencia { get; set; }
        public string CelularContactoEmergencia { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public string TextoCatalogoTipoCuenta { get; set; }
    }
}
