//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEstudios
    {
        public int IDDetalleEstudios { get; set; }
        public Nullable<int> TipoEstudio { get; set; }
        public Nullable<int> Institucion { get; set; }
        public Nullable<int> Titulo { get; set; }
        public Nullable<int> AnioFinalizacion { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public Nullable<int> Pais { get; set; }
        public int FichaIngresoID { get; set; }
    }
}
