//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCodificacionEquipo
    {
        public int IDDetalleCodificacionEquipo { get; set; }
        public int CodificacionEquipoID { get; set; }
        public string Codigo { get; set; }
        public string Factura { get; set; }
        public int EquipoID { get; set; }
        public string SerieEquipo { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public string Observaciones { get; set; }
        public string Adjunto { get; set; }
    }
}
