//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosAdjuntosIngreso
    {
        public int IDDocumentoAdjuntosIngreso { get; set; }
        public string NombreArchivo { get; set; }
        public string TipoArchivo { get; set; }
        public byte[] ArchivoAdjunto { get; set; }
        public int IngresoID { get; set; }
        public int UsuarioID { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public bool Estado { get; set; }
    }
}
