//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class DocumentosPendientesCobroP2P
    {
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string ReferenciaFactura { get; set; }
        public Nullable<System.Guid> ReferenciaAlterna { get; set; }
        public string DocumentoDelComprador { get; set; }
        public string NombreDelComprador { get; set; }
        public Nullable<decimal> ValorFacturaDecimal { get; set; }
        public string ValorFactura { get; set; }
        public string FechaVencimiento { get; set; }
        public string ValorRecargo { get; set; }
        public string FechaCorte { get; set; }
        public int CodigoRecargo { get; set; }
    }
}
