//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosAdjuntosIngreso
    {
        public int IDDocumentoAdjuntosIngreso { get; set; }
        public string NombreArchivo { get; set; }
        public string TipoArchivo { get; set; }
        public byte[] ArchivoAdjunto { get; set; }
        public int IngresoID { get; set; }
        public int UsuarioID { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public bool Estado { get; set; }
    }
}
