//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class EquiposInfo
    {
        public int IDEquipo { get; set; }
        public string NombreEquipo { get; set; }
        public string DescripcionEquipo { get; set; }
        public int Tipo { get; set; }
        public string TextoCatalogoTipo { get; set; }
        public string IDsCaracteristicas { get; set; }
        public string Caracteristicas { get; set; }
        public string Observaciones { get; set; }
        public bool EstadoEquipo { get; set; }
        public string TextoEstadoEquipo { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public int Proveedor { get; set; }
        public string TextoCatalogoProveedor { get; set; }
        public string CodigoCatalogoTipo { get; set; }
    }
}
