//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaIngreso
    {
        public int IDFichaIngreso { get; set; }
        public int UsuarioID { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> Genero { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public Nullable<int> LugarNacimiento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> CiudadResidencia { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public Nullable<int> Banco { get; set; }
        public string NumeroCuentaBancaria { get; set; }
        public Nullable<int> TipoSangre { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public System.DateTime FechaIngresoFicha { get; set; }
        public string DireccionCallePrincipal { get; set; }
        public string DireccionCalleSecundaria { get; set; }
        public string DireccionNumeroCasa { get; set; }
        public string DireccionConjuntoResidencial { get; set; }
        public string NombresContactoEmergencia { get; set; }
        public string ApellidosContactoEmergencia { get; set; }
        public Nullable<int> ParentescoContactoEmergencia { get; set; }
        public string TelefonoContactoEmergencia { get; set; }
        public string CelularContactoEmergencia { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public string Referencia { get; set; }
        public string Sector { get; set; }
    }
}
