//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class FichasIngresosInfo
    {
        public int IDFichaIngreso { get; set; }
        public int UsuarioID { get; set; }
        public string NombresUsuario { get; set; }
        public string ApellidosUsuario { get; set; }
        public string NombresApellidosUsuario { get; set; }
        public string identificacion { get; set; }
        public string username { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Clave { get; set; }
        public string TextoEstadoUsuario { get; set; }
        public Nullable<bool> EstadoUsuario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Cargo { get; set; }
        public string TextoCatalogoCargo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string NombreEmpresa { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string NombreRol { get; set; }
        public string DescripcionRol { get; set; }
        public Nullable<bool> EstadoRol { get; set; }
        public Nullable<bool> ResetClave { get; set; }
        public Nullable<bool> ValidacionCorreo { get; set; }
        public string TokenValidacionCorreo { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> Genero { get; set; }
        public string TextoCatalogoGenero { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public string TextoCatalogoNacionalidad { get; set; }
        public Nullable<int> LugarNacimiento { get; set; }
        public string TextoCatalogoLugarNacimiento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> CiudadResidencia { get; set; }
        public string TextoCatalogoCiudadResidencia { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public string TextoCatalogoEstadoCivil { get; set; }
        public Nullable<int> Banco { get; set; }
        public string TextoCatalogoBanco { get; set; }
        public string NumeroCuentaBancaria { get; set; }
        public Nullable<int> TipoSangre { get; set; }
        public string TextoCatalogoTipoSangre { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public System.DateTime FechaIngresoFicha { get; set; }
        public string DireccionCallePrincipal { get; set; }
        public string DireccionCalleSecundaria { get; set; }
        public string DireccionNumeroCasa { get; set; }
        public string DireccionConjuntoResidencial { get; set; }
        public string NombresContactoEmergencia { get; set; }
        public string ApellidosContactoEmergencia { get; set; }
        public Nullable<int> ParentescoContactoEmergencia { get; set; }
        public string TextoCatalogoParentescoContactoEmergencia { get; set; }
        public string TelefonoContactoEmergencia { get; set; }
        public string CelularContactoEmergencia { get; set; }
        public bool Estado { get; set; }
        public string TextoEstado { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public string TextoCatalogoTipoCuenta { get; set; }
    }
}
