//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class InformacionEquipoCodificacionInfo
    {
        public int IDDetalleCodificacionEquipo { get; set; }
        public int CodificacionEquipoID { get; set; }
        public string Factura { get; set; }
        public int EquipoID { get; set; }
        public string NombreEquipo { get; set; }
        public string DescripcionEquipo { get; set; }
        public string TextoCatalogoTipo { get; set; }
        public string CodigoCatalogoTipo { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Proveedor { get; set; }
        public string TextoCatalogoProveedor { get; set; }
        public string Caracteristicas { get; set; }
        public string IDsCaracteristicas { get; set; }
        public string ObservacionesEquipo { get; set; }
        public Nullable<bool> EstadoEquipo { get; set; }
        public string TextoEstadoEquipo { get; set; }
        public string Codigo { get; set; }
        public string SerieEquipo { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public string ObservacionesDetalleCodificacion { get; set; }
        public string Adjunto { get; set; }
        public Nullable<int> UsuarioID { get; set; }
    }
}
