//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class IngresoUsuarioDesvinculacionInfo
    {
        public int IdUsuario { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NombresApellidos { get; set; }
        public string Identificacion { get; set; }
        public string MailCorporativo { get; set; }
        public string Mail { get; set; }
        public string Username { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IDFichaIngreso { get; set; }
        public Nullable<int> IDIngreso { get; set; }
        public Nullable<int> IDDesvinculacionPersonal { get; set; }
        public int TieneFichaIngreso { get; set; }
        public int TieneIngreso { get; set; }
        public int PersonaDesvinculada { get; set; }
    }
}
