//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int IDIngreso { get; set; }
        public Nullable<int> TipoIngreso { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Departamento { get; set; }
        public string PersonaReemplazante { get; set; }
        public string CorreoAsignado { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public int FichaIngresoID { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> JefeDirecto { get; set; }
        public Nullable<int> Cargo { get; set; }
        public Nullable<int> TipoContrato { get; set; }
        public Nullable<int> GrupoCorreo { get; set; }
        public string CredencialAcceso { get; set; }
    }
}
