//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int IdMenu { get; set; }
        public string NombreMenu { get; set; }
        public string NombrePaginaMenu { get; set; }
        public Nullable<bool> EstadoMenu { get; set; }
        public Nullable<int> IdMenuPadre { get; set; }
        public Nullable<int> OrdenMenu { get; set; }
    }
}
