//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class NotificacionesInfo
    {
        public long IDNotificaciones { get; set; }
        public string NombreTarea { get; set; }
        public string DescripcionTarea { get; set; }
        public string NombreEmisor { get; set; }
        public string CorreoEmisor { get; set; }
        public string ClaveCorreo { get; set; }
        public string CorreosDestinarios { get; set; }
        public string AsuntoCorreo { get; set; }
        public string NombreArchivoPlantillaCorreo { get; set; }
        public string CuerpoCorreo { get; set; }
        public string AdjuntosCorreo { get; set; }
        public System.DateTime FechaEnvioCorreo { get; set; }
        public bool EstadoNotificacion { get; set; }
        public Nullable<bool> EstadoEnviadoNotificacion { get; set; }
        public bool EstadoEjecucionNotificacion { get; set; }
        public string DetalleEstadoEjecucionNotificacion { get; set; }
        public string Empresa { get; set; }
        public string Canal { get; set; }
        public string Tipo { get; set; }
        public string EstadoActivacionNotificacion { get; set; }
        public string EstadoEnColaNotificacion { get; set; }
        public string EstadoEnvioNotificacion { get; set; }
    }
}
