//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class OperationResultDB
    {
        public string Respuesta { get; set; }
        public Nullable<decimal> IdentityEntidad { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public Nullable<int> Error { get; set; }
        public Nullable<int> ErrorState { get; set; }
        public Nullable<int> ErrorLine { get; set; }
        public string ErrorProcedure { get; set; }
    }
}
