//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class PerfilInfo
    {
        public int IdPerfil { get; set; }
        public string NombrePerfil { get; set; }
        public string DescripcionPerfil { get; set; }
        public Nullable<bool> EstadoPerfil { get; set; }
        public string TextoEstadoPerfil { get; set; }
    }
}
