//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class RequerimientoEquipoInfo
    {
        public int IDRequerimientoEquipo { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int UsuarioID { get; set; }
        public bool EstadoRequerimientoEquipo { get; set; }
        public string Equipos { get; set; }
        public string IDsEquipos { get; set; }
        public string HerramientasAdicionales { get; set; }
        public string IDsHerramientasAdicionales { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string Clave { get; set; }
        public string TextoEstadoUsuario { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Cargo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string NombreEmpresa { get; set; }
        public string NombreRol { get; set; }
        public string DescripcionRol { get; set; }
        public Nullable<bool> EstadoRol { get; set; }
        public string Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string NombresApellidos { get; set; }
        public string Username { get; set; }
        public Nullable<int> Area { get; set; }
        public string TextoCatalogoArea { get; set; }
        public string TextoCatalogoDepartamento { get; set; }
        public string TextoCatalogoCargo { get; set; }
        public string TextoCatalogoPais { get; set; }
        public string TextoCatalogoCiudad { get; set; }
        public string TextoEstadoRol { get; set; }
        public Nullable<bool> EstadoUsuario { get; set; }
        public int UsuarioSolicitanteID { get; set; }
        public string NombresSolicitante { get; set; }
        public string TextoEstadoRequerimientoEquipo { get; set; }
        public bool Asignado { get; set; }
        public string TextoAsignadoRequerimientoEquipo { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public string TextoAprobadoRequerimientoEquipo { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public string CredencialAcceso { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> JefeDirecto { get; set; }
        public string TextoCatalogoJefeDirecto { get; set; }
        public string PersonaReemplazante { get; set; }
        public Nullable<int> TipoIngreso { get; set; }
        public string TextoCatalogoTipoIngreso { get; set; }
        public string CorreoAsignado { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public string EquiposSugeridosCargoUsuario { get; set; }
        public string IDsEquiposSugeridosCargoUsuario { get; set; }
        public Nullable<int> TipoContrato { get; set; }
        public string TextoCatalogoTipoContrato { get; set; }
        public string ProveedorEquipos { get; set; }
        public string CostoEquipos { get; set; }
        public string MailCorporativo { get; set; }
        public Nullable<bool> TieneCodificacion { get; set; }
        public Nullable<System.DateTime> FechaEstimadaEntregaEquipos { get; set; }
        public Nullable<int> GrupoCorreo { get; set; }
        public string TextoCatalogoGrupoCorreo { get; set; }
    }
}
