//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RRHHEntities : DbContext
    {
        public RRHHEntities()
            : base("name=RRHHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionEquipo> AsignacionEquipo { get; set; }
        public virtual DbSet<AsignacionEquipoUsuario> AsignacionEquipoUsuario { get; set; }
        public virtual DbSet<DetalleCargasFamiliares> DetalleCargasFamiliares { get; set; }
        public virtual DbSet<DetalleEstudios> DetalleEstudios { get; set; }
        public virtual DbSet<DetalleExperiencias> DetalleExperiencias { get; set; }
        public virtual DbSet<DocumentosAdjuntosIngreso> DocumentosAdjuntosIngreso { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<EquipoCaracteristica> EquipoCaracteristica { get; set; }
        public virtual DbSet<FichaIngreso> FichaIngreso { get; set; }
        public virtual DbSet<Ingreso> Ingreso { get; set; }
        public virtual DbSet<RequerimientoEquipo> RequerimientoEquipo { get; set; }
        public virtual DbSet<RequerimientoEquipoHerramientasAdicionales> RequerimientoEquipoHerramientasAdicionales { get; set; }
        public virtual DbSet<RequerimientoEquipoUsuario> RequerimientoEquipoUsuario { get; set; }
        public virtual DbSet<SugerenciaEquiposCargo> SugerenciaEquiposCargo { get; set; }
        public virtual DbSet<SugerenciaEquiposCargoProgramas> SugerenciaEquiposCargoProgramas { get; set; }
        public virtual DbSet<CodificacionEquipo> CodificacionEquipo { get; set; }
        public virtual DbSet<DesvinculacionPersonal> DesvinculacionPersonal { get; set; }
        public virtual DbSet<DetalleEquiposEntregados> DetalleEquiposEntregados { get; set; }
        public virtual DbSet<ComentariosRequerimientoEquipo> ComentariosRequerimientoEquipo { get; set; }
        public virtual DbSet<DetalleCodificacionEquipo> DetalleCodificacionEquipo { get; set; }
    
        public virtual ObjectResult<IngresosInfo> ListadoIngresos(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IngresosInfo>("ListadoIngresos", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<FichasIngresosInfo> ListadoFichasIngresos(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FichasIngresosInfo>("ListadoFichasIngresos", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<EquiposInfo> ListadoEquipos(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EquiposInfo>("ListadoEquipos", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<DetalleExperienciasInfo> ListadoDetalleExperiencias(Nullable<int> iDDetalle, Nullable<int> iDFichaIngreso)
        {
            var iDDetalleParameter = iDDetalle.HasValue ?
                new ObjectParameter("IDDetalle", iDDetalle) :
                new ObjectParameter("IDDetalle", typeof(int));
    
            var iDFichaIngresoParameter = iDFichaIngreso.HasValue ?
                new ObjectParameter("IDFichaIngreso", iDFichaIngreso) :
                new ObjectParameter("IDFichaIngreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleExperienciasInfo>("ListadoDetalleExperiencias", iDDetalleParameter, iDFichaIngresoParameter);
        }
    
        public virtual ObjectResult<DetalleEstudiosInfo> ListadoDetalleEstudios(Nullable<int> iDDetalle, Nullable<int> iDFichaIngreso)
        {
            var iDDetalleParameter = iDDetalle.HasValue ?
                new ObjectParameter("IDDetalle", iDDetalle) :
                new ObjectParameter("IDDetalle", typeof(int));
    
            var iDFichaIngresoParameter = iDFichaIngreso.HasValue ?
                new ObjectParameter("IDFichaIngreso", iDFichaIngreso) :
                new ObjectParameter("IDFichaIngreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleEstudiosInfo>("ListadoDetalleEstudios", iDDetalleParameter, iDFichaIngresoParameter);
        }
    
        public virtual ObjectResult<DetalleCargasFamiliaresInfo> ListadoDetalleCargasFamiliares(Nullable<int> iDDetalle, Nullable<int> iDFichaIngreso)
        {
            var iDDetalleParameter = iDDetalle.HasValue ?
                new ObjectParameter("IDDetalle", iDDetalle) :
                new ObjectParameter("IDDetalle", typeof(int));
    
            var iDFichaIngresoParameter = iDFichaIngreso.HasValue ?
                new ObjectParameter("IDFichaIngreso", iDFichaIngreso) :
                new ObjectParameter("IDFichaIngreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCargasFamiliaresInfo>("ListadoDetalleCargasFamiliares", iDDetalleParameter, iDFichaIngresoParameter);
        }
    
        public virtual ObjectResult<AsignacionEquipoInfo> ListadoAsignacionEquipo(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AsignacionEquipoInfo>("ListadoAsignacionEquipo", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<SugerenciaEquiposCargo> ConsultarSugerenciaEquiposCargo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SugerenciaEquiposCargo>("ConsultarSugerenciaEquiposCargo", idParameter);
        }
    
        public virtual ObjectResult<SugerenciaEquiposCargo> ConsultarSugerenciaEquiposCargo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SugerenciaEquiposCargo>("ConsultarSugerenciaEquiposCargo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<RequerimientoEquipoUsuario> ConsultarRequerimientoEquipoUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoEquipoUsuario>("ConsultarRequerimientoEquipoUsuario", idParameter);
        }
    
        public virtual ObjectResult<RequerimientoEquipoUsuario> ConsultarRequerimientoEquipoUsuario(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoEquipoUsuario>("ConsultarRequerimientoEquipoUsuario", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<RequerimientoEquipoHerramientasAdicionales> ConsultarRequerimientoEquipoHerramientasAdicionales(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoEquipoHerramientasAdicionales>("ConsultarRequerimientoEquipoHerramientasAdicionales", idParameter);
        }
    
        public virtual ObjectResult<RequerimientoEquipoHerramientasAdicionales> ConsultarRequerimientoEquipoHerramientasAdicionales(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoEquipoHerramientasAdicionales>("ConsultarRequerimientoEquipoHerramientasAdicionales", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<RequerimientoEquipo> ConsultarRequerimientoEquipo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoEquipo>("ConsultarRequerimientoEquipo", idParameter);
        }
    
        public virtual ObjectResult<RequerimientoEquipo> ConsultarRequerimientoEquipo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoEquipo>("ConsultarRequerimientoEquipo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<Ingreso> ConsultarIngreso(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ingreso>("ConsultarIngreso", idParameter);
        }
    
        public virtual ObjectResult<Ingreso> ConsultarIngreso(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ingreso>("ConsultarIngreso", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<FichaIngreso> ConsultarFichaIngreso(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FichaIngreso>("ConsultarFichaIngreso", idParameter);
        }
    
        public virtual ObjectResult<FichaIngreso> ConsultarFichaIngreso(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FichaIngreso>("ConsultarFichaIngreso", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<Equipo> ConsultarEquipo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Equipo>("ConsultarEquipo", idParameter);
        }
    
        public virtual ObjectResult<Equipo> ConsultarEquipo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Equipo>("ConsultarEquipo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<DocumentosAdjuntosIngreso> ConsultarDocumentoAdjuntosIngreso(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocumentosAdjuntosIngreso>("ConsultarDocumentoAdjuntosIngreso", idParameter);
        }
    
        public virtual ObjectResult<DocumentosAdjuntosIngreso> ConsultarDocumentoAdjuntosIngreso(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocumentosAdjuntosIngreso>("ConsultarDocumentoAdjuntosIngreso", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<DetalleExperiencias> ConsultarDetalleExperiencias(Nullable<int> id, Nullable<int> fichaIngresoID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fichaIngresoIDParameter = fichaIngresoID.HasValue ?
                new ObjectParameter("FichaIngresoID", fichaIngresoID) :
                new ObjectParameter("FichaIngresoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleExperiencias>("ConsultarDetalleExperiencias", idParameter, fichaIngresoIDParameter);
        }
    
        public virtual ObjectResult<DetalleExperiencias> ConsultarDetalleExperiencias(Nullable<int> id, Nullable<int> fichaIngresoID, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fichaIngresoIDParameter = fichaIngresoID.HasValue ?
                new ObjectParameter("FichaIngresoID", fichaIngresoID) :
                new ObjectParameter("FichaIngresoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleExperiencias>("ConsultarDetalleExperiencias", mergeOption, idParameter, fichaIngresoIDParameter);
        }
    
        public virtual ObjectResult<DetalleEstudios> ConsultarDetalleEstudios(Nullable<int> id, Nullable<int> fichaIngresoID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fichaIngresoIDParameter = fichaIngresoID.HasValue ?
                new ObjectParameter("FichaIngresoID", fichaIngresoID) :
                new ObjectParameter("FichaIngresoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleEstudios>("ConsultarDetalleEstudios", idParameter, fichaIngresoIDParameter);
        }
    
        public virtual ObjectResult<DetalleEstudios> ConsultarDetalleEstudios(Nullable<int> id, Nullable<int> fichaIngresoID, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fichaIngresoIDParameter = fichaIngresoID.HasValue ?
                new ObjectParameter("FichaIngresoID", fichaIngresoID) :
                new ObjectParameter("FichaIngresoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleEstudios>("ConsultarDetalleEstudios", mergeOption, idParameter, fichaIngresoIDParameter);
        }
    
        public virtual ObjectResult<DetalleCargasFamiliares> ConsultarDetalleCargasFamiliares(Nullable<int> id, Nullable<int> fichaIngresoID)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fichaIngresoIDParameter = fichaIngresoID.HasValue ?
                new ObjectParameter("FichaIngresoID", fichaIngresoID) :
                new ObjectParameter("FichaIngresoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCargasFamiliares>("ConsultarDetalleCargasFamiliares", idParameter, fichaIngresoIDParameter);
        }
    
        public virtual ObjectResult<DetalleCargasFamiliares> ConsultarDetalleCargasFamiliares(Nullable<int> id, Nullable<int> fichaIngresoID, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var fichaIngresoIDParameter = fichaIngresoID.HasValue ?
                new ObjectParameter("FichaIngresoID", fichaIngresoID) :
                new ObjectParameter("FichaIngresoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCargasFamiliares>("ConsultarDetalleCargasFamiliares", mergeOption, idParameter, fichaIngresoIDParameter);
        }
    
        public virtual ObjectResult<AsignacionEquipo> ConsultarAsignacionesEquipo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AsignacionEquipo>("ConsultarAsignacionesEquipo", idParameter);
        }
    
        public virtual ObjectResult<AsignacionEquipo> ConsultarAsignacionesEquipo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AsignacionEquipo>("ConsultarAsignacionesEquipo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<AsignacionEquipoUsuario> ConsultarAsignacionEquipoUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AsignacionEquipoUsuario>("ConsultarAsignacionEquipoUsuario", idParameter);
        }
    
        public virtual ObjectResult<AsignacionEquipoUsuario> ConsultarAsignacionEquipoUsuario(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AsignacionEquipoUsuario>("ConsultarAsignacionEquipoUsuario", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<RequerimientoEquipoInfo> ListadoRequerimientoEquipo(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoEquipoInfo>("ListadoRequerimientoEquipo", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<SugerenciaEquiposCargoInfo> ListadoSugerenciaEquiposCargo(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SugerenciaEquiposCargoInfo>("ListadoSugerenciaEquiposCargo", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<CodificacionEquipo> ConsultarCodificacionEquipo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CodificacionEquipo>("ConsultarCodificacionEquipo", idParameter);
        }
    
        public virtual ObjectResult<CodificacionEquipo> ConsultarCodificacionEquipo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CodificacionEquipo>("ConsultarCodificacionEquipo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<DetalleCodificacionEquipo> ConsultarDetalleCodificacionEquipo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCodificacionEquipo>("ConsultarDetalleCodificacionEquipo", idParameter);
        }
    
        public virtual ObjectResult<DetalleCodificacionEquipo> ConsultarDetalleCodificacionEquipo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCodificacionEquipo>("ConsultarDetalleCodificacionEquipo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<CodificacionEquipoInfo> ListadoCodificacionEquipo(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CodificacionEquipoInfo>("ListadoCodificacionEquipo", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<DetalleCodificacionEquipoInfo> ListadoDetalleCodificacionEquipo(Nullable<int> iDDetalle, Nullable<int> iDCodificacionEquipo)
        {
            var iDDetalleParameter = iDDetalle.HasValue ?
                new ObjectParameter("IDDetalle", iDDetalle) :
                new ObjectParameter("IDDetalle", typeof(int));
    
            var iDCodificacionEquipoParameter = iDCodificacionEquipo.HasValue ?
                new ObjectParameter("IDCodificacionEquipo", iDCodificacionEquipo) :
                new ObjectParameter("IDCodificacionEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleCodificacionEquipoInfo>("ListadoDetalleCodificacionEquipo", iDDetalleParameter, iDCodificacionEquipoParameter);
        }
    
        public virtual ObjectResult<RequerimientoUsuarioInfo> ListadoRequerimientoUsuario(Nullable<int> requerimientoquipoid)
        {
            var requerimientoquipoidParameter = requerimientoquipoid.HasValue ?
                new ObjectParameter("requerimientoquipoid", requerimientoquipoid) :
                new ObjectParameter("requerimientoquipoid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoUsuarioInfo>("ListadoRequerimientoUsuario", requerimientoquipoidParameter);
        }
    
        public virtual ObjectResult<RequerimientoUsuarioHerramientasadicionalesInfo> ListadoRequerimientoUsuarioHerramientasadicionales(Nullable<int> requerimientoquipoid)
        {
            var requerimientoquipoidParameter = requerimientoquipoid.HasValue ?
                new ObjectParameter("requerimientoquipoid", requerimientoquipoid) :
                new ObjectParameter("requerimientoquipoid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RequerimientoUsuarioHerramientasadicionalesInfo>("ListadoRequerimientoUsuarioHerramientasadicionales", requerimientoquipoidParameter);
        }
    
        public virtual ObjectResult<DesvinculacionPersonal> ConsultarDesvinculacionPersonal(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DesvinculacionPersonal>("ConsultarDesvinculacionPersonal", idParameter);
        }
    
        public virtual ObjectResult<DesvinculacionPersonal> ConsultarDesvinculacionPersonal(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DesvinculacionPersonal>("ConsultarDesvinculacionPersonal", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<DetalleEquiposEntregados> ConsultarDetalleEquiposEntregados(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleEquiposEntregados>("ConsultarDetalleEquiposEntregados", idParameter);
        }
    
        public virtual ObjectResult<DetalleEquiposEntregados> ConsultarDetalleEquiposEntregados(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleEquiposEntregados>("ConsultarDetalleEquiposEntregados", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<DesvinculacionPersonalInfo> ListadoDesvinculacionPersonal(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DesvinculacionPersonalInfo>("ListadoDesvinculacionPersonal", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<DetalleEquiposEntregadosInfo> ListadoDetalleEquiposEntregados(Nullable<int> iDDetalle, Nullable<int> iDDesvinculacionPersonal)
        {
            var iDDetalleParameter = iDDetalle.HasValue ?
                new ObjectParameter("IDDetalle", iDDetalle) :
                new ObjectParameter("IDDetalle", typeof(int));
    
            var iDDesvinculacionPersonalParameter = iDDesvinculacionPersonal.HasValue ?
                new ObjectParameter("IDDesvinculacionPersonal", iDDesvinculacionPersonal) :
                new ObjectParameter("IDDesvinculacionPersonal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DetalleEquiposEntregadosInfo>("ListadoDetalleEquiposEntregados", iDDetalleParameter, iDDesvinculacionPersonalParameter);
        }
    
        public virtual ObjectResult<ComentariosRequerimientoEquipo> ConsultaComentariosRequerimientoEquipo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComentariosRequerimientoEquipo>("ConsultaComentariosRequerimientoEquipo", idParameter);
        }
    
        public virtual ObjectResult<ComentariosRequerimientoEquipo> ConsultaComentariosRequerimientoEquipo(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComentariosRequerimientoEquipo>("ConsultaComentariosRequerimientoEquipo", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<ComentariosRequerimientoEquipoInfo> ListadoComentariosRequerimientoEquipo(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ComentariosRequerimientoEquipoInfo>("ListadoComentariosRequerimientoEquipo", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<AprobacionRequerimientoEquipoInfo> ListadoAprobacionRequerimientoEquipo(Nullable<long> pagenum, string searchText, string filtro)
        {
            var pagenumParameter = pagenum.HasValue ?
                new ObjectParameter("pagenum", pagenum) :
                new ObjectParameter("pagenum", typeof(long));
    
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AprobacionRequerimientoEquipoInfo>("ListadoAprobacionRequerimientoEquipo", pagenumParameter, searchTextParameter, filtroParameter);
        }
    
        public virtual ObjectResult<EquiposAsignadosUsuariosRequerimientosInfo> ListadoEquiposAsignadosUsuariosRequerimientos(Nullable<int> usuarioID)
        {
            var usuarioIDParameter = usuarioID.HasValue ?
                new ObjectParameter("UsuarioID", usuarioID) :
                new ObjectParameter("UsuarioID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EquiposAsignadosUsuariosRequerimientosInfo>("ListadoEquiposAsignadosUsuariosRequerimientos", usuarioIDParameter);
        }
    
        public virtual ObjectResult<IngresosInfo> ConsultarIngresoPorFicha(Nullable<int> idFichaIngreso)
        {
            var idFichaIngresoParameter = idFichaIngreso.HasValue ?
                new ObjectParameter("idFichaIngreso", idFichaIngreso) :
                new ObjectParameter("idFichaIngreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IngresosInfo>("ConsultarIngresoPorFicha", idFichaIngresoParameter);
        }
    
        public virtual ObjectResult<InformacionEquipoCodificacionInfo> ConsultarInformacionEquipoCodificacion(Nullable<int> iD, Nullable<int> usuarioID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var usuarioIDParameter = usuarioID.HasValue ?
                new ObjectParameter("UsuarioID", usuarioID) :
                new ObjectParameter("UsuarioID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InformacionEquipoCodificacionInfo>("ConsultarInformacionEquipoCodificacion", iDParameter, usuarioIDParameter);
        }
    
        public virtual ObjectResult<IngresoUsuarioDesvinculacionInfo> ListadoIngresoUsuarioDesvinculacion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<IngresoUsuarioDesvinculacionInfo>("ListadoIngresoUsuarioDesvinculacion");
        }
    }
}
