//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SugerenciaEquiposCargoProgramas
    {
        public int IDSugerenciaEquiposCargoProgramas { get; set; }
        public Nullable<int> Programa { get; set; }
        public Nullable<int> SugerenciaEquiposCargoID { get; set; }
    }
}
