//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SugerenciaEquiposCargo
    {
        public int IDSugerenciaEquiposCargo { get; set; }
        public int EquipoID { get; set; }
        public int Cargo { get; set; }
        public string Observaciones { get; set; }
        public int UsuarioID { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> Empresa { get; set; }
    }
}
