//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SugerenciaEquiposCargoProgramas
    {
        public int IDSugerenciaEquiposCargoProgramas { get; set; }
        public Nullable<int> Programa { get; set; }
        public Nullable<int> SugerenciaEquiposCargoID { get; set; }
    }
}
