//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SugerenciaEquiposCargo
    {
        public int IDSugerenciaEquiposCargo { get; set; }
        public int EquipoID { get; set; }
        public int Cargo { get; set; }
        public string Observaciones { get; set; }
        public int UsuarioID { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> Empresa { get; set; }
    }
}
