//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class TipoNotificacionesInfo
    {
        public int IdNotificacion { get; set; }
        public string NombreNotificacion { get; set; }
        public string DescripcionNotificacion { get; set; }
        public Nullable<int> TiempoEspera { get; set; }
        public Nullable<bool> EstadoNotificacion { get; set; }
        public string TextoEstadoNotificacion { get; set; }
    }
}
