//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    
    public partial class UsuarioRolMenuPermisoInfo
    {
        public int IDRolMenuPermiso { get; set; }
        public int RolID { get; set; }
        public string NombreRol { get; set; }
        public int PerfilID { get; set; }
        public string NombrePerfil { get; set; }
        public int MenuID { get; set; }
        public string NombreMenu { get; set; }
        public string EnlaceMenu { get; set; }
        public string MenuPadre { get; set; }
        public int IDCatalogo { get; set; }
        public string CodigoCatalogo { get; set; }
        public string TextoCatalogoAccion { get; set; }
        public string MetodoControlador { get; set; }
        public string NombreControlador { get; set; }
        public string AccionEnlace { get; set; }
        public Nullable<int> CreadoPorID { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<int> ActualizadoPorID { get; set; }
        public string ActualizadoPor { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public bool Estado { get; set; }
    }
}
