//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntradaSalidaRRHH.DAL.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Username { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> Cargo { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Mail { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string MailCorporativo { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string Clave { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> ResetClave { get; set; }
        public Nullable<bool> ValidacionCorreo { get; set; }
        public string TokenValidacionCorreo { get; set; }
        public Nullable<int> CiudadUbicacionEmpresa { get; set; }
    }
}
