USE RRHH
GO
/*****************  Tarea 1  ************************
	Proyecto: RRHH									*
	Fecha: 09/feb/2021
	Descripción: Empresa: Retirar del listado Finzo, 
		Evaluar , cambiar APS PTV por  Kickoff / outside
		box por OPINO
*****************************************************/

DELETE FROM adm.Catalogo WHERE NombreCatalogo IN ('FINZO')
UPDATE adm.Catalogo SET NombreCatalogo = 'KICKOFF', CodigoCatalogo = 'KICKOFF' WHERE CodigoCatalogo = 'PTV'
UPDATE adm.Catalogo SET NombreCatalogo = 'OPINO', CodigoCatalogo = 'OPINO' WHERE CodigoCatalogo = 'OSTB'
GO
/*****************  Tarea 3  ************************
	Proyecto: RRHH									*
	Fecha: 10/feb/2021
	Descripción: "Estado Civil: Aumentar en el catálogo 
	""Unión de Hecho"""
*****************************************************/
DECLARE @CatalogoPadre INT
SELECT @CatalogoPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = 'ESTADO-CIVIL-01'
INSERT INTO adm.Catalogo (CodigoCatalogo, NombreCatalogo, DescripcionCatalogo, IdCatalogoPadre, EstadoCatalogo,IdEmpresa,Eliminado)
VALUES (NULL,'UNIÓN DE HECHO','UNIÓN DE HECHO', @CatalogoPadre, 1, 1, 0)
GO
/*****************  Tarea 18  ************************
	Proyecto: RRHH									*
	Fecha: 19/feb/2021
	Descripción: Referencia: Crear este nuevo campo 
		en Dirección (obligatorio)
*****************************************************/
ALTER TABLE FichaIngreso ADD Referencia VARCHAR(100)
GO

/*****************  Tarea 19  ************************
	Proyecto: RRHH									*
	Fecha: 19/feb/2021
	Descripción: Sector: Crear este nuevo campo 
		en Dirección (obligatorio)
*****************************************************/
ALTER TABLE FichaIngreso ADD Sector VARCHAR(100)
GO
/*****************  Tarea 25  ************************
	Proyecto: RRHH									*
	Fecha: 19/feb/2021
	Descripción: Tipo de Estudio: El Catálogo debe
		contener Bachiller/Tercer Nivel/Postgrado
*****************************************************/
DECLARE @CatalogoPadre INT
SELECT @CatalogoPadre= IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = 'TIPO-ESTUDIO-01'


UPDATE adm.Catalogo SET NombreCatalogo = 'TERCER NIVEL', DescripcionCatalogo = 'TERCER NIVEL' 
WHERE IdCatalogoPadre = @CatalogoPadre AND NombreCatalogo = 'UNIVERSITARIO'

UPDATE adm.Catalogo SET NombreCatalogo = 'POSTGRADO', DescripcionCatalogo = 'POSTGRADO' 
WHERE IdCatalogoPadre = @CatalogoPadre AND NombreCatalogo = 'CUARTO NIVEL'
GO
/*****************  Tarea 25  ************************
	Proyecto: RRHH									*
	Fecha: 19/feb/2021
	Descripción: parentesco: Agregar nuevo campo 
	con una lista desplegable que contenga a 
	Cónyuge e Hijos
*****************************************************/


DECLARE @CodigoCatalogo VARCHAR(20) = 'CARGA-FAM'
INSERT INTO adm.Catalogo VALUES (@CodigoCatalogo, 'CARGAS FAMILIARES', 'CARGAS FAMILIARES',NULL, 1,1,0)

DECLARE @CatalogoPadre INT
SELECT @CatalogoPadre= IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @CodigoCatalogo

INSERT INTO adm.Catalogo VALUES 
(NULL, 'CONYUGUE', 'CONYUGUE', @CatalogoPadre, 1,1,0),
(NULL, 'HIJO/A', 'HIJO/A', @CatalogoPadre, 1,1,0)

ALTER TABLE DetalleCargasFamiliares ADD Parentesco INT

GO
/*****************  Tarea 25  ************************
	Proyecto: RRHH									*
	Fecha: 19/feb/2021
	Descripción: Generar un check junto al campo Año 
	de Finalización que permita escoger entre las 
	opciones de Finalizado y En Curso, este chek 
	debe habilitarse siempre y cuando se escoja el 
	año actual
*****************************************************/
ALTER TABLE DetalleEstudios ADD FINALIZADO BIT
GO
DECLARE @AñoActual INT = YEAR(GETDATE())
UPDATE DetalleEstudios SET Finalizado = 1 WHERE AnioFinalizacion < @AñoActual
UPDATE DetalleEstudios SET Finalizado = 0 WHERE AnioFinalizacion = @AñoActual
GO
/*****************  Tarea 33  ************************
	Proyecto: RRHH									*
	Fecha: 22/feb/2021
	Descripción: Generar un nuevo botón que permita 
	únicamente visualizar la ficha de ingreso, esto 
	es para el caso del usuario de la Doctora que 
	ella necesita ver los datos del nuevo empleado.
*****************************************************/
DECLARE @Rol VARCHAR(20) = 'MEDICO'
DECLARE @Perfil VARCHAR(20) = 'VISUALIZADOR FICHA INGRESO'
DECLARE @RolId INT
DECLARE @PerfilId INT
DECLARE @MenuId INT

INSERT INTO adm.Rol VALUES(@Rol, 'ROL QUE PERMITE VISUALIZACION DE USUARIOS',1)
INSERT INTO adm.Perfil VALUES(@Perfil,'VISUALIZACION FICHA INGRESO',1)

SELECT @RolId = IdRol FROM adm.Rol WHERE Nombre = @Rol
SELECT @PerfilId = IdPerfil FROM adm.Perfil WHERE NombrePerfil = @Perfil

INSERT INTO  adm.RolPerfil VALUES (@RolId, @PerfilId)

SELECT @MenuId = IdMenu FROM adm.Menu WHERE NombreMenu = 'Ficha de Ingreso'

INSERT INTO adm.PerfilMenu VALUES (@PerfilId, @MenuId)

DECLARE @PadreAccionSistema VARCHAR(50) = 'ACCIONES-SIST-01'
DECLARE @VisualizarAccionSistema VARCHAR(50)= 'ACCIONES-SIST-VISUALIZAR-REGISTRO'
DECLARE @IdPadre INT
DECLARE @IdVisualizarAccion INT
SELECT @IdPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @PadreAccionSistema

INSERT INTO adm.Catalogo VALUES(@VisualizarAccionSistema,'VISUALIZAR REGISTRO','_IndexGrid',@IdPadre,1,1,0)

SELECT @IdVisualizarAccion = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @VisualizarAccionSistema 

INSERT INTO adm.RolMenuPermiso VALUES (@RolId, @PerfilId, @MenuId,@IdVisualizarAccion,1,1,GETDATE(), GETDATE(),1)

GO
/*****************  Tarea 39  ************************
	Proyecto: RRHH									*
	Fecha: 23/feb/2021
	Descripción: En campo tipo de ingreso agregar 
	honorarios y pasantia.
*****************************************************/
DECLARE @CatalogoPadre INT
SELECT @CatalogoPadre= IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = 'TIPO-INGRE-01'

DECLARE @NombreCatalogo1 VARCHAR(20) = 'HONORARIOS'
INSERT INTO adm.Catalogo VALUES (NULL, @NombreCatalogo1, 'INGRESO POR HONORARIOS', @CatalogoPadre, 1,1,0)
DECLARE @NombreCatalogo2 VARCHAR(20) = 'PASANTIA'
INSERT INTO adm.Catalogo VALUES (NULL, @NombreCatalogo2, 'INGRESO POR PASANTIAS', @CatalogoPadre, 1,1,0)
GO

/*****************  Tarea 38  ************************
	Proyecto: RRHH									*
	Fecha: 23/feb/2021
	Descripción: En campo empresa cambiar: APS PTV 
		por  Kickoff / outiside box por OPINO.
*****************************************************/
DECLARE @CatalogoPadre INT
SELECT @CatalogoPadre= IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = 'EMP-01'

DECLARE @NombreCatalogo1 VARCHAR(20) = 'ATIS PTV'
UPDATE adm.Catalogo SET CodigoCatalogo ='KICKOFF', NombreCatalogo = 'KICKOFF', DescripcionCatalogo = 'KICKOFF' WHERE NombreCatalogo = @NombreCatalogo1

DECLARE @NombreCatalogo2 VARCHAR(20) = 'OUTSIDE THE BOX '
UPDATE adm.Catalogo SET CodigoCatalogo = 'OPINO', NombreCatalogo = 'OPINO', DescripcionCatalogo = 'OPINO' WHERE NombreCatalogo = @NombreCatalogo2
GO

/*****************  Tarea 4  ************************
	Proyecto: RRHH									*
	Fecha: 23/feb/2021
	Descripción:
	Bancos: Cargar los todos los bancos
*****************************************************/

DECLARE @IdPadre INT
SELECT @IdPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = 'BANCO-01'
DELETE FROM adm.Catalogo WHERE IdCatalogoPadre = @IdPadre
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO CENTRAL DEL ECUADOR','BANCO CENTRAL DEL ECUADOR',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO PICHINCHA','BANCO PICHINCHA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DE GUAYAQUIL S.A','BANCO DE GUAYAQUIL S.A',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO CITY BANK','BANCO CITY BANK',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO MACHALA','BANCO MACHALA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DE LOJA','BANCO DE LOJA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DEL PACIFICO','BANCO DEL PACIFICO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO INTERNACIONAL','BANCO INTERNACIONAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO AMAZONAS','BANCO AMAZONAS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DEL AUSTRO','BANCO DEL AUSTRO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'PRODUBANCO / PROMERICA','PRODUBANCO / PROMERICA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO BOLIVARIANO','BANCO BOLIVARIANO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COMERCIAL DE MANABI','COMERCIAL DE MANABI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO GENERAL RUMINAHUI S.A.','BANCO GENERAL RUMINAHUI S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DEL LITORAL S.A.','BANCO DEL LITORAL S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO SOLIDARIO','BANCO SOLIDARIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO PROCREDIT S.A.','BANCO PROCREDIT S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO CAPITAL','BANCO CAPITAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DESARROLLO DE LOS PUEBLOS S.A.','BANCO DESARROLLO DE LOS PUEBLOS S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANECUADOR B.P.','BANECUADOR B.P.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO 15 DE ABRIL LTDA','COOP. AHORRO Y CREDITO 15 DE ABRIL LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. JARDIN AZUAYO','COOP. JARDIN AZUAYO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO POLICIA NACIONAL','COOP.DE AHORRO Y CREDITO POLICIA NACIONAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'FINANCOOP','FINANCOOP',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DELBANK S.A.','BANCO DELBANK S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO ECUATORIANO DE LA VIVIENDA','BANCO ECUATORIANO DE LA VIVIENDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CACPECO LTDA','CACPECO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C.PEQ.EMPRESA DE PASTAZA','C.PEQ.EMPRESA DE PASTAZA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO 23 DE JULIO','COOP. AHORRO Y CREDITO 23 DE JULIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO 29 DE OCTUBRE','COOP. AHORRO Y CREDITO 29 DE OCTUBRE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO ANDALUCIA','COOP. AHORRO Y CREDITO ANDALUCIA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO COTOCOLLAO','COOP. AHORRO Y CREDITO COTOCOLLAO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO EL SAGRARIO','COOP. AHORRO Y CREDITO EL SAGRARIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO GUARANDA LTDA','COOP. AHORRO Y CREDITO GUARANDA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. JUVENTUD ECUATORIANA PROGRESISTA LTDA.','COOP. JUVENTUD ECUATORIANA PROGRESISTA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO MANUEL','COOP. AHORRO Y CREDITO MANUEL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO OSCUS','COOP. AHORRO Y CREDITO OSCUS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO PABLO MUNOZ VEGA','COOP. AHORRO Y CREDITO PABLO MUNOZ VEGA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO PROGRESO','COOP. AHORRO Y CREDITO PROGRESO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO RIOBAMBA','COOP. AHORRO Y CREDITO RIOBAMBA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO SAN FRANCISCO','COOP. AHORRO Y CREDITO SAN FRANCISCO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO TULCAN','COOP. AHORRO Y CREDITO TULCAN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO ATUNTAQUI LTDA.','COOP. DE AHORRO Y CREDITO ATUNTAQUI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO COMERCIO LTDA PORTOVIEJO','COOP. DE AHORRO Y CREDITO COMERCIO LTDA PORTOVIEJO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO LA DOLOROSA LTDA','COOP. DE AHORRO Y CREDITO LA DOLOROSA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. PREVISION AHORRO Y DESARROLLO','COOP. PREVISION AHORRO Y DESARROLLO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.AHORRO Y CREDITO ALIANZA DEL VALLE LTDA','COOP.AHORRO Y CREDITO ALIANZA DEL VALLE LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO CONSTRC COMERCIO Y PRODUC','COOP AHORRO Y CREDITO CONSTRC COMERCIO Y PRODUC',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.AHORRO Y CREDITO CHONE LTDA','COOP.AHORRO Y CREDITO CHONE LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SANTA ANA LTDA','COOPERATIVA DE AHORRO Y CREDITO SANTA ANA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'FINANCIERA - DINERS CLUB DEL ECUADOR','FINANCIERA - DINERS CLUB DEL ECUADOR',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'MUTUALISTA AMBATO','MUTUALISTA AMBATO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'MUTUALISTA AZUAY','MUTUALISTA AZUAY',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'MUTUALISTA IMBABURA','MUTUALISTA IMBABURA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'MUTUALISTA PICHINCHA','MUTUALISTA PICHINCHA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. CORPORACION CENTRO LTDA.','COOP DE A. Y C. CORPORACION CENTRO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CORDILLERA DE LOS ANDES LTDA.','COOP. DE A. Y C. CORDILLERA DE LOS ANDES LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. PUERTO FRANCISCO DE ORELLANA','COOP. DE A. Y C. PUERTO FRANCISCO DE ORELLANA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A Y C. LUZ DEL VALLE','COOP. DE A Y C. LUZ DEL VALLE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A Y C. ESPERANZA Y PROGRESO DEL VALLE','COOP. DE A Y C. ESPERANZA Y PROGRESO DEL VALLE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CHOCO TUNGURAHUA RUNA LTDA','COOP. DE A. Y C. CHOCO TUNGURAHUA RUNA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. COOPARTAMOS LTDA','COOP. DE A. Y C. COOPARTAMOS LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. EMPRENDEDORES COOPEMPRENDER LTDA.','COOP. DE A. Y C. EMPRENDEDORES COOPEMPRENDER LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. NUEVA LOJA LTDA.','COOP. DE A. Y C. NUEVA LOJA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. PICHNCHA LTDA.','COOP. DE A. Y C. PICHNCHA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. CREDITO Y AHORRO SAN FRANCISCO DE ASIS','COOP. CREDITO Y AHORRO SAN FRANCISCO DE ASIS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO CACEC LTDA. (COTOPAXI)','COOP.DE AHORRO Y CREDITO CACEC LTDA. (COTOPAXI)',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE A. Y C. VENCEDORES DE PICHINCHA LTDA.','COOP.DE A. Y C. VENCEDORES DE PICHINCHA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SAN BARTOLO LTDA','COOPERATIVA DE AHORRO Y CREDITO SAN BARTOLO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. DEL EMIGRANTE ECUATORIANO Y SU FA','COOP. DE A. Y C. DEL EMIGRANTE ECUATORIANO Y SU FA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO LA LIBERTAD LTDA','COOP. AHORRO Y CREDITO LA LIBERTAD LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC CUNA DE LA NACIONALIDAD LTDA.','COAC CUNA DE LA NACIONALIDAD LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO MACODES LTDA','COOPERATIVA DE AHORRO Y CREDITO MACODES LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SANTA ISABEL LTDA.','COOPERATIVA DE AHORRO Y CREDITO SANTA ISABEL LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO GANANSOL LTDA','COOPERATIVA DE AHORRO Y CREDITO GANANSOL LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO DEL AZUAY','COOPERATIVA DE AHORRO Y CREDITO DEL AZUAY',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO DEL COLEGIO DE ARQ','COOPERATIVA DE AHORRO Y CREDITO DEL COLEGIO DE ARQ',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO NUKANCHIK','COOPERATIVA DE AHORRO Y CREDITO NUKANCHIK',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO SANTA ANA CUENCA','COOP DE AHORRO Y CREDITO SANTA ANA CUENCA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO MULTIEMPRESARIAL L','COOPERATIVA DE AHORRO Y CREDITO MULTIEMPRESARIAL L',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC DEL SINDICATO DE CHOFERES PROFESIONALES DEL A','COAC DEL SINDICATO DE CHOFERES PROFESIONALES DEL A',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO JUAN DE SALINAS LTDA.','COOP. AHORRO Y CREDITO JUAN DE SALINAS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO PUELLARO LTDA','COOP. AHORRO Y CREDITO PUELLARO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO NUEVA JERUSALEN','COOP. AHORRO Y CREDITO NUEVA JERUSALEN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO MALCHINGUI LTDA.','COOP. AHORRO Y CREDITO MALCHINGUI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO CHOLA CUENCANA LTDA.','COOP. DE AHORRO Y CREDITO CHOLA CUENCANA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO TENA LTDA.','COOP. AHORRO Y CREDITO TENA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO DE LA PEQUENA EMPRESA GUALA','COOP. AHORRO Y CREDITO DE LA PEQUENA EMPRESA GUALA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO ALIANZA MINAS LTDA.','COOP. AHORRO Y CREDITO ALIANZA MINAS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO PEDRO MONCAYO LTDA.','COOP. DE AHORRO Y CREDITO PEDRO MONCAYO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO PROVIDA','COOPERATIVA DE AHORRO Y CREDITO PROVIDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SAN JOSE S.J.','COOPERATIVA DE AHORRO Y CREDITO SAN JOSE S.J.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO SENOR DE GIRON','COOP. AHORRO Y CREDITO SENOR DE GIRON',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO EDUC.DEL TUNGURAHUA LTDA','COOP. DE AHORRO Y CREDITO EDUC.DEL TUNGURAHUA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA 15 DE AGOSTO PILACOTO','COOPERATIVA 15 DE AGOSTO PILACOTO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO CRISTO REY','COOP. DE AHORRO Y CREDITO CRISTO REY',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO EDUCADORES DE CHIMBORAZO','COOP. DE AHORRO Y CREDITO EDUCADORES DE CHIMBORAZO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO MINGA LTDA.','COOPERATIVA DE AHORRO Y CREDITO MINGA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO 4 DE OCTUBRE LTDA.','COOP. DE AHORRO Y CREDITO 4 DE OCTUBRE LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO CREDI FACIL LTDA.','COOP. DE AHORRO Y CREDITO CREDI FACIL LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO ALFONSO JARAMILLO C.C.C.','COOP. DE AHORRO Y CREDITO ALFONSO JARAMILLO C.C.C.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. INDIGENA SAC PELILEO','COOP. DE A. Y C. INDIGENA SAC PELILEO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. INTERCULTURAL TAWANTINSUYU LTDA.','COOP. DE A. Y C. INTERCULTURAL TAWANTINSUYU LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. OCIPSA','COOP. DE A. Y C. OCIPSA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 21 DE NOVIEMBRE LTDA.','COOP. DE A. Y C. 21 DE NOVIEMBRE LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. LA FLORESTA LTDA.','COOP. DE A. Y C. LA FLORESTA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CORP. ORG. CAMPESINAS DE QUISAPIN','COOP. DE A. Y C. CORP. ORG. CAMPESINAS DE QUISAPIN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. MULTICULTURAL BANCO INDIGENA LTDA','COOP. DE A. Y C. MULTICULTURAL BANCO INDIGENA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. CRECER WINARI LTDA.','COOP DE A. Y C. CRECER WINARI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. BANOS DE AGUA SANTA LTDA.','COOP. DE A. Y C. BANOS DE AGUA SANTA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO 1 DE JULIO','COOP. DE AHORRO Y CREDITO 1 DE JULIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SUMAK NAN LTDA.','COOP. DE A. Y C. SUMAK NAN LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO CANAR LTDA.','COOPERATIVA DE AHORRO Y CREDITO CANAR LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SAN ANTONIO LTDA.','COOPERATIVA DE AHORRO Y CREDITO SAN ANTONIO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO FUNDAR','COOP. DE AHORRO Y CREDITO FUNDAR',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO METROPOLIS LTDA.','COOP. AHORRO Y CREDITO METROPOLIS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO EL CAFETAL','COOP. DE AHORRO Y CREDITO EL CAFETAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO MICROEMPRESARIAL SUCRE','COOP.DE AHORRO Y CREDITO MICROEMPRESARIAL SUCRE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. AFROECUATORIANA DE LA PEQ. EMP. L','COOP. DE A. Y C. AFROECUATORIANA DE LA PEQ. EMP. L',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO JOYOCOTO LTDA.','COOPERATIVA DE AHORRO Y CREDITO JOYOCOTO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO SAN ANTONIO LTDA.','COOP. AHORRO Y CREDITO SAN ANTONIO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. UNIOTAVALO LTDA.','COOP. DE A. Y C. UNIOTAVALO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. UNION EL EJIDO','COOP. DE A. Y C. UNION EL EJIDO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. GENESIS LTDA.','COOP. DE A. Y C. GENESIS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A Y C. MARIA AUXILIADORA DE QUIROGA LTDA','COOP. DE A Y C. MARIA AUXILIADORA DE QUIROGA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. FORTALEZA','COOP. DE A. Y C. FORTALEZA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO PARA LA ASISTENCIA COMUNITARIA FINCA S.A.','BANCO PARA LA ASISTENCIA COMUNITARIA FINCA S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. CALCETA LTDA','COOP. CALCETA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO 9 DE OCTUBRE LTDA','COOP. AHORRO Y CREDITO 9 DE OCTUBRE LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO D LA PEQ EMPR CACPE BIBLIAN','COOP. AHORRO Y CREDITO D LA PEQ EMPR CACPE BIBLIAN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO SAN GABRIEL LTDA.','COOP. AHORRO Y CREDITO SAN GABRIEL LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO SAN JOSE LTDA','COOP. AHORRO Y CREDITO SAN JOSE LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO SAN MIGUEL DE LOS BANCOS','COOP. AHORRO Y CREDITO SAN MIGUEL DE LOS BANCOS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO SEMILLA DEL PROGRESO LTDA','COOP. AHORRO Y CREDITO SEMILLA DEL PROGRESO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO. Y CREDI. MUJERES UNIDAS TANTANAKUSHK','COOP. AHORRO. Y CREDI. MUJERES UNIDAS TANTANAKUSHK',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CRED. SANTA ROSA LTDA','COOP. DE AHORRO Y CRED. SANTA ROSA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO ONCE DE JUNIO','COOP. DE AHORRO Y CREDITO ONCE DE JUNIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. PUJILI LTDA','COOP. DE A. Y C. PUJILI LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CREDIL LTDA.','COOP. DE A. Y C. CREDIL LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. MUSHUK PAKARI LTDA.','COOP. DE A. Y C. MUSHUK PAKARI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. UNIBLOCK Y SERVICIOS LTDA.','COOP. DE A. Y C. UNIBLOCK Y SERVICIOS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SAN FERNANDO LIMITADA','COOP. DE A. Y C. SAN FERNANDO LIMITADA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. FUTURO LAMANENSE','COOP. DE A. Y C. FUTURO LAMANENSE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SAQUISILI LTDA.','COOP. DE A. Y C. SAQUISILI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. INNOVACION ANDINA LTDA.','COOP. DE A. Y C. INNOVACION ANDINA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE A.Y C. EL COMERCIANTE LTDA (MIES)','COOP.DE A.Y C. EL COMERCIANTE LTDA (MIES)',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. MUSHUK WASI LTDA ( MIES )','COOP. DE A. Y C. MUSHUK WASI LTDA ( MIES )',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SOLIDARIA LTDA','COOPERATIVA DE AHORRO Y CREDITO SOLIDARIA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO LLANGANATES','COOPERATIVA DE AHORRO Y CREDITO LLANGANATES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'INTERDIN S.A.','INTERDIN S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.AHO Y CREDITO DE LA PEQ. EMP. DE LOJA CACPE','COOP.AHO Y CREDITO DE LA PEQ. EMP. DE LOJA CACPE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO ECONOMIA DEL SUR C','COOPERATIVA DE AHORRO Y CREDITO ECONOMIA DEL SUR C',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO MIGRANTES Y EMPREN','COOPERATIVA DE AHORRO Y CREDITO MIGRANTES Y EMPREN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SAN SEBASTIAN','COOPERATIVA DE AHORRO Y CREDITO SAN SEBASTIAN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. DEL SINDICATO DE CHOFERES PROFESI','COOP. DE A. Y C. DEL SINDICATO DE CHOFERES PROFESI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO 29 DE ENERO','COOP.DE AHORRO Y CREDITO 29 DE ENERO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO AGRARIA MUSHUK KAWSAY LTDA.','COOP. AHORRO Y CREDITO AGRARIA MUSHUK KAWSAY LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO RUNA SHUNGO LTDA.','COOPERATIVA DE AHORRO Y CREDITO RUNA SHUNGO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SAN MARCOS','COOP. DE A. Y C. SAN MARCOS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. ANTORCHA LTDA.','COOP. DE A. Y C. ANTORCHA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SOCIO AMIGO','COOPERATIVA DE AHORRO Y CREDITO SOCIO AMIGO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. INDIGENAS GALAPAGOS LTDA.','COOP. DE A. Y C. INDIGENAS GALAPAGOS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO CAMARA DE COMERCIO DEL CANT','COOP. AHORRO Y CREDITO CAMARA DE COMERCIO DEL CANT',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO LA BENEFICA LTDA.','COOPERATIVA DE AHORRO Y CREDITO LA BENEFICA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO ABDON CALDERON LTDA.','COOP.DE AHORRO Y CREDITO ABDON CALDERON LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. A Y C CAMARA DE COMERCIO CANTON -EL CARMEN L','COOP. A Y C CAMARA DE COMERCIO CANTON -EL CARMEN L',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO AGROPRODUCTIVA MANABI LTD','COOP.DE AHORRO Y CREDITO AGROPRODUCTIVA MANABI LTD',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CRED. LA INMACULADA DE SAN PLACI','COOP. DE AHORRO Y CRED. LA INMACULADA DE SAN PLACI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO CACPE MANABI','COOP. AHORRO Y CREDITO CACPE MANABI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.AHORRO Y CREDITO MAGISTERIO MANABITA LIMITADA','COOP.AHORRO Y CREDITO MAGISTERIO MANABITA LIMITADA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC TIENDA DE DINERO LTDA.','COAC TIENDA DE DINERO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.A.Y C. SANTA MARIA DE LA MANGA DEL CURA LTDA.','COOP.A.Y C. SANTA MARIA DE LA MANGA DEL CURA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO CAMARA DE COMERCIO INDIGENA','COOP. AHORRO Y CREDITO CAMARA DE COMERCIO INDIGENA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. GUAMOTE LTDA.','COOP. DE A. Y C. GUAMOTE LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A.Y C. PRODUC. AHORRO INVERS. SERVICIO P.','COOP. DE A.Y C. PRODUC. AHORRO INVERS. SERVICIO P.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. FRANDESC LTDA.','COOP. DE A. Y C. FRANDESC LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. NUKA LLAKTA LTDA.','COOP. DE A. Y C. NUKA LLAKTA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A Y C. CAMARA DE COMERCIO RIOBAMBA','COOP. DE A Y C. CAMARA DE COMERCIO RIOBAMBA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. BASHALAN LTDA.','COOP. DE A. Y C. BASHALAN LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CAMARA DE COMERCIO SANTO DOMINGO','COOP. DE A. Y C. CAMARA DE COMERCIO SANTO DOMINGO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. EDUCADORES TULCAN LTDA.','COOP. DE A. Y C. EDUCADORES TULCAN LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. WARMIKUNAPAK RIKCHARI','COOP. WARMIKUNAPAK RIKCHARI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO MI TIERRA','COOP AHORRO Y CREDITO MI TIERRA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO DE LA PEQ EMP CACPE YANZATZA','COOP AHORRO Y CREDITO DE LA PEQ EMP CACPE YANZATZA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO FUNDESARROLLO','COOP AHORRO Y CREDITO FUNDESARROLLO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CAJA ECUAESPANA','CAJA ECUAESPANA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO NUEVA HUANCAVILCA','COOP DE AHORRO Y CREDITO NUEVA HUANCAVILCA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO ERCO LTDA','COOP DE AHORRO Y CREDITO ERCO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO CAMARA COMERCIO DE AMBATO','COOP AHORRO Y CREDITO CAMARA COMERCIO DE AMBATO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO MUSHUC RUNA LTDA','COOP AHORRO Y CREDITO MUSHUC RUNA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO AMBATO LTDA','COOP DE AHORRO Y CREDITO AMBATO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO DORADO LTDA','COOP DE AHORRO Y CREDITO DORADO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO NUESTROS ABUELOS LTDA','COOP DE AHORRO Y CREDITO NUESTROS ABUELOS LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO ARTESANOS LTDA','COOP DE AHORRO Y CREDITO ARTESANOS LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO SANTA ANITA LTDA','COOP DE AHORRO Y CREDITO SANTA ANITA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO HUAYCO PUNGO LTDA','COOP DE AHORRO Y CREDITO HUAYCO PUNGO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP MANUEL ESTEBAN GODOY ORTEGA LTDA COOPMEGO','COOP MANUEL ESTEBAN GODOY ORTEGA LTDA COOPMEGO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO PADRE JULIAN LORENTE LTDA','COOP AHORRO Y CREDITO PADRE JULIAN LORENTE LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AHORRO Y CREDITO CARIAMANGA LTDA','COOP AHORRO Y CREDITO CARIAMANGA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO MARCABELI LTDA','COOP DE AHORRO Y CREDITO MARCABELI LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO AGRICOLA JUNIN LTDA','COOP DE AHORRO Y CREDITO AGRICOLA JUNIN LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO PUERTO LOPEZ LTDA','COOP DE AHORRO Y CREDITO PUERTO LOPEZ LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO NUEVA ESPERANZA','COOP DE AHORRO Y CREDITO NUEVA ESPERANZA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO SAN JORGE LTDA','COOP DE AHORRO Y CREDITO SAN JORGE LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO FERNANDO DAQUILEMA','COOP DE AHORRO Y CREDITO FERNANDO DAQUILEMA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C EDUCADORES DE PASTAZA LTDA','COOP DE A Y C EDUCADORES DE PASTAZA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. A. Y C. DE LA PEQ. EMP. CACPE ZAMORA LTDA','COOP. A. Y C. DE LA PEQ. EMP. CACPE ZAMORA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. DESARROLLO INTEGRAL LTDA','COOP. DE A. Y C. DESARROLLO INTEGRAL LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO EL CALVARIO LTDA','COOP. DE AHORRO Y CREDITO EL CALVARIO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. JUAN PIO DE MORA LTDA','COOP. DE A. Y C. JUAN PIO DE MORA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO PILAHUIN','COOP. DE AHORRO Y CREDITO PILAHUIN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO PUCARA LTDA','COOP. DE AHORRO Y CREDITO PUCARA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. A. Y C. CAMARA DE COMERCIO DE PINDAL CADECOP','COOP. A. Y C. CAMARA DE COMERCIO DE PINDAL CADECOP',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO DEL INSTITU ECUATORIANO DE SEGURIDAD SOCIAL','BANCO DEL INSTITU ECUATORIANO DE SEGURIDAD SOCIAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C DE SERV PUBL DEL MIN EDUCACION Y CUL','COOP DE A Y C DE SERV PUBL DEL MIN EDUCACION Y CUL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C 23 DE MAYO LTDA','COOP DE A Y C 23 DE MAYO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C COCA LTDA','COOP DE A Y C COCA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO PILAHUIN TIO LTDA','COOP DE AHORRO Y CREDITO PILAHUIN TIO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO HUAICANA LTDA','COOP DE AHORRO Y CREDITO HUAICANA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C CREDISUR LTDA','COOP DE A Y C CREDISUR LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'FONDO DE CESANTIA DEL MAGISTERIO ECUAT FCME-FCPC','FONDO DE CESANTIA DEL MAGISTERIO ECUAT FCME-FCPC',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO HUAQUILLAS LTDA','COOP DE AHORRO Y CREDITO HUAQUILLAS LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C BANOS LTDA','COOP DE A Y C BANOS LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO CAC-CICA MIES','COOP DE AHORRO Y CREDITO CAC-CICA MIES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C VENCEDORES DE TUNGURAHUA','COOP DE A Y C VENCEDORES DE TUNGURAHUA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C ECUAFUTURO LTDA','COOP A Y C ECUAFUTURO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C MAQUITA CUSHUN LTDA','COOP DE A Y C MAQUITA CUSHUN LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C VALLES DEL LIRIO','COOP DE A Y C VALLES DEL LIRIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP ESFUERZO UNIDO PARA EL DESARR DEL CHILCO','COOP ESFUERZO UNIDO PARA EL DESARR DEL CHILCO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C CARROCEROS DE TUNGURAHUA','COOP A Y C CARROCEROS DE TUNGURAHUA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO SIMIATUG LTDA','COOP DE AHORRO Y CREDITO SIMIATUG LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C SINCHI RUNA LTDA','COOP DE A Y C SINCHI RUNA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C SANTA ROSA DE PAUTAN LTDA','COOP DE A Y C SANTA ROSA DE PAUTAN LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO SAN MIGUEL DE SIGCHOS','COOP DE AHORRO Y CREDITO SAN MIGUEL DE SIGCHOS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C SIERRA CENTRO LTDA','COOP DE A Y C SIERRA CENTRO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C GONZANAMA MIES','COOP DE A Y C GONZANAMA MIES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO QUILANGA LTDA','COOP DE AHORRO Y CREDITO QUILANGA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO 27 DE ABRIL LOJA','COOP DE AHORRO Y CREDITO 27 DE ABRIL LOJA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C CREDIAMIGO LTDA LOJA MIES','COOP DE A Y C CREDIAMIGO LTDA LOJA MIES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO FORTUNA MIES','COOP DE AHORRO Y CREDITO FORTUNA MIES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C PROFESIONALES DEL VOLANTE UNION LTDA','COOP A Y C PROFESIONALES DEL VOLANTE UNION LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO CACPE CELICA','COOP DE AHORRO Y CREDITO CACPE CELICA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C FUTURO Y PROGRESO DE GALAPAGOS LTDA','COOP DE A Y C FUTURO Y PROGRESO DE GALAPAGOS LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C SUMAC LLACTA LTDA','COOP DE A Y C SUMAC LLACTA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C LUCHA CAMPESINA LTDA','COOP DE A Y C LUCHA CAMPESINA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C MAQUITA CUSHUNCHIC LTDA','COOP DE A Y C MAQUITA CUSHUNCHIC LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C FOCLA','COOP A Y C FOCLA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C CASAG LTDA','COOP DE A Y C CASAG LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO D MIRO SA','BANCO D MIRO SA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C GENERAL RUMINAHUI','COOP DE A Y C GENERAL RUMINAHUI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C FINANCIERA INDIGENA LTDA','COOP DE A Y C FINANCIERA INDIGENA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C 20 FEBRERO LTDA','COOP A Y C 20 FEBRERO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C DEL COL. FISC. VICENTE ROCAFUERTE','COOP DE A Y C DEL COL. FISC. VICENTE ROCAFUERTE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C JADAN LTDA (MIES)','COOP DE A Y C JADAN LTDA (MIES)',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C INKA KIPU LTDA','COOP DE A Y C INKA KIPU LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C ACCION TUNGURAHUA LTDA','COOP DE A Y C ACCION TUNGURAHUA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C PIJAL','COOP DE A Y C PIJAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C ESCENCIA INDIGENA LTDA','COOP DE A Y C ESCENCIA INDIGENA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C UNION MERCEDARIA LTDA','COOP DE A Y C UNION MERCEDARIA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C CATAMAYO LTDA','COOP DE A Y C CATAMAYO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C DE LA PEQ EMPRESA CACPE MACARA','COOP DE A Y C DE LA PEQ EMPRESA CACPE MACARA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C NUEVOS HORIZONTES EL ORO LTDA','COOP A Y C NUEVOS HORIZONTES EL ORO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'BANCO COOPNACIONAL SA','BANCO COOPNACIONAL SA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C 16 DE JUNIO','COOP DE A Y C 16 DE JUNIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C ESC SUP POLITEC AGROP DE MANABI MANUEL','COOP A Y C ESC SUP POLITEC AGROP DE MANABI MANUEL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO FASAYNAN LTDA','COOP DE AHORRO Y CREDITO FASAYNAN LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP CACIQUE GURITAVE','COOP CACIQUE GURITAVE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP SOLIDARIDAD Y PROGRESO ORIENTAL','COOP SOLIDARIDAD Y PROGRESO ORIENTAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHO Y CRED LOS ANDES LATINOS LTDA.','COOP. DE AHO Y CRED LOS ANDES LATINOS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C. DE A. Y C COOPAC AUSTRO LTDA (MIESS)','C. DE A. Y C COOPAC AUSTRO LTDA (MIESS)',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SALASACA','COOP. DE A. Y C. SALASACA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SUMAK SAMY LTDA.','COOP. DE A. Y C. SUMAK SAMY LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C. A. Y C. INTERCULT. TARPUK RUNA LTDA.','C. A. Y C. INTERCULT. TARPUK RUNA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. VIRGEN DEL CISNE','COOP. DE A. Y C. VIRGEN DEL CISNE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C. DE A Y C EDUCAD. DE ZAMORA CHINCHIPE','C. DE A Y C EDUCAD. DE ZAMORA CHINCHIPE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C. DE AH. Y CREDITO LAS LAGUNAS (MIESS)','C. DE AH. Y CREDITO LAS LAGUNAS (MIESS)',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C. DE A Y C. EDUCADORES DE EL ORO LTD','C. DE A Y C. EDUCADORES DE EL ORO LTD',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C DE A Y C EMPLEAD BANCAR DEL ORO LTDA','C DE A Y C EMPLEAD BANCAR DEL ORO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AH. Y CREDITO RIOCHICO','COOPERATIVA DE AH. Y CREDITO RIOCHICO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C. DE A. Y C. SAN MARTIN DE TISALEO LTDA.','C. DE A. Y C. SAN MARTIN DE TISALEO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. ALLI TARPUC LTDA.','COOP. DE A. Y C. ALLI TARPUC LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'C. DE A Y C. SAN MIGUEL DE PALLATANGA','C. DE A Y C. SAN MIGUEL DE PALLATANGA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A Y C FENIX','COOP DE A Y C FENIX',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO CAMARA DE COMERCIO DE LOJ','COOP.DE AHORRO Y CREDITO CAMARA DE COMERCIO DE LOJ',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE A. Y C. DE CRECIMIENTO ECONOMICO RENTABLE','COOP.DE A. Y C. DE CRECIMIENTO ECONOMICO RENTABLE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SANTIAGO LTDA','COOPERATIVA DE AHORRO Y CREDITO SANTIAGO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE A. Y C. POPULAR Y SOLIDARIA','COOP.DE A. Y C. POPULAR Y SOLIDARIA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO SAN PLACIDO LTDA.','COOP.DE AHORRO Y CREDITO SAN PLACIDO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE AHORRO Y CREDITO CIUDAD DE ZAMORA','COOP.DE AHORRO Y CREDITO CIUDAD DE ZAMORA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A Y C DE LA PEQUENA EMPRESA DE PALORA','COOP. DE A Y C DE LA PEQUENA EMPRESA DE PALORA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. INDIGENA ALFA Y OMEGA LTDA','COOP. DE A. Y C. INDIGENA ALFA Y OMEGA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO CREA LTDA ( MIES)','COOPERATIVA DE AHORRO Y CREDITO CREA LTDA ( MIES)',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CHIBULEO LTDA.','COOP. DE A. Y C. CHIBULEO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. EL TESORO PILLARENO','COOP. DE A. Y C. EL TESORO PILLARENO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. KISAPINCHA LTDA.','COOP. DE A. Y C. KISAPINCHA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. JUVENTUD UNIDA LTDA.','COOP. DE A. Y C. JUVENTUD UNIDA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. UNION QUISAPINCHA LTDA.','COOP. DE A. Y C. UNION QUISAPINCHA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 13 DE ABRIL LTDA','COOP. DE A. Y C. 13 DE ABRIL LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SALINAS LTDA.','COOP. DE A. Y C. SALINAS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SAN PEDRO LTDA.','COOP. DE A. Y C. SAN PEDRO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. LOS CHASQUIS PASTOCALLE LTDA.','COOP. DE A. Y C. LOS CHASQUIS PASTOCALLE LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. COOPINDIGENA LTDA.','COOP. DE A. Y C. COOPINDIGENA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. LA UNION LTDA.','COOP. DE A. Y C. LA UNION LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. PADRE VICENTE PONCE RUBIO','COOP. DE A. Y C. PADRE VICENTE PONCE RUBIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. MUSHUG CAUSAY LTDA.','COOP. DE A. Y C. MUSHUG CAUSAY LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 29 DE AGOSTO','COOP. DE A. Y C. 29 DE AGOSTO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CREDISOCIO','COOP. DE A. Y C. CREDISOCIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. FONDO PARA EL DESARROLLO Y LA VID','COOP. DE A. Y C. FONDO PARA EL DESARROLLO Y LA VID',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE A Y C NUEVA VISION','COOPERATIVA DE A Y C NUEVA VISION',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO FOCASH LTDA.','COOP. DE AHORRO Y CREDITO FOCASH LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SAN VICENTE DEL SUR LTDA.','COOP. DE A. Y C. SAN VICENTE DEL SUR LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. PARA LA VIVIENDA ORDEN Y SEGURIDA','COOP. DE A. Y C. PARA LA VIVIENDA ORDEN Y SEGURIDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. CAMARA DE COMERCIO JOYA DE LOS SAC','COOP DE A. Y C. CAMARA DE COMERCIO JOYA DE LOS SAC',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. FOCAP','COOP. DE A. Y C. FOCAP',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 18 DE NOVIEMBRE','COOP. DE A. Y C. 18 DE NOVIEMBRE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO DR. CORNELIO SAENZ','COOPERATIVA DE AHORRO Y CREDITO DR. CORNELIO SAENZ',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. EDUCADORES DEL AZUAY','COOP DE A. Y C. EDUCADORES DEL AZUAY',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. INDIGENA SAC LTDA','COOP. DE A. Y C. INDIGENA SAC LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CREDI YA LTDA','COOP. DE A. Y C. CREDI YA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SAN BARTOLOME LTDA','COOP. DE A. Y C. SAN BARTOLOME LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO MUSHUK YUYAY','COOP. DE AHORRO Y CREDITO MUSHUK YUYAY',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. SISAY KANARI','COOP DE A. Y C. SISAY KANARI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE A Y C ACCION IMBABURAPAK LTDA.','COOPERATIVA DE A Y C ACCION IMBABURAPAK LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. HERMES GAIBOR VERDESOTO','COOP DE A. Y C. HERMES GAIBOR VERDESOTO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SEMILLAS DE PANGUA','COOP. DE A. Y C. SEMILLAS DE PANGUA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE A Y C MUSHUK SOLIDARIA','COOPERATIVA DE A Y C MUSHUK SOLIDARIA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. PANAMERICANA LTDA','COOP DE A. Y C. PANAMERICANA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. VILCABAMBA CACVIL','COOP. DE A. Y C. VILCABAMBA CACVIL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. FAMILIA SOLIDARIA','COOP. DE A. Y C. FAMILIA SOLIDARIA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO EL PARAISO MANGA D','COOPERATIVA DE AHORRO Y CREDITO EL PARAISO MANGA D',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC DE LOS PROFESORES EMPLEADOS Y TRABAJADORES DE','COAC DE LOS PROFESORES EMPLEADOS Y TRABAJADORES DE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC. SANTA ROSA DE SAN CARLOS LTDA.','COAC. SANTA ROSA DE SAN CARLOS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CONSTRUCTOR DEL DESARROLLO SOLIDA','COOP. DE A. Y C. CONSTRUCTOR DEL DESARROLLO SOLIDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. MUSHUK YUYAY LTDA','COOP DE A. Y C. MUSHUK YUYAY LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CORPORACION FINANCIERA','CORPORACION FINANCIERA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. ALIANZA SOCIAL ECU. ALSEC','COOP. DE A. Y C. ALIANZA SOCIAL ECU. ALSEC',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. RENOVADORA ECU','COOP. DE A. Y C. RENOVADORA ECU',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. MUSHUK YUYAY - NAPO','COOP. DE A. Y C. MUSHUK YUYAY - NAPO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SANTA ANA DE NAYON','COOP. DE A. Y C. SANTA ANA DE NAYON',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. EDUCADORES DEL NAPO','COOP. DE A. Y C. EDUCADORES DEL NAPO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE A. Y C. TEXTIL 14 DE MARZO','COOPERATIVA DE A. Y C. TEXTIL 14 DE MARZO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A Y C SAN CARLOS LTDA.','COOP. DE A Y C SAN CARLOS LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC A Y C ESPERANZA DE VALLE DE LA VIRGEN LTDA.','COAC A Y C ESPERANZA DE VALLE DE LA VIRGEN LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC A Y C ZONA DE CAPITAL CORCIMOL','COAC A Y C ZONA DE CAPITAL CORCIMOL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP.DE A. Y C. ARTESANAL DEL AZUAY','COOP.DE A. Y C. ARTESANAL DEL AZUAY',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO SUMAK SISA','COOPERATIVA DE AHORRO Y CREDITO SUMAK SISA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. REY DAVID LTDA','COOP. DE A. Y C. REY DAVID LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. KULLKI WASI LTDA.','COOP. DE A. Y C. KULLKI WASI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. SINCHI CODEFIS','COOP DE A. Y C. SINCHI CODEFIS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. FUERZA DE LOS ANDES','COOP. DE A. Y C. FUERZA DE LOS ANDES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. CAMINO DE LUZ LTDA.','COOP DE A. Y C. CAMINO DE LUZ LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC A Y C EDUCADORES DE BOLIVAR','COAC A Y C EDUCADORES DE BOLIVAR',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC SAN MIGUEL LTDA.','COAC SAN MIGUEL LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SALINERITA','COOP. DE A. Y C. SALINERITA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. BOLA AMARILLA','COOP. DE A. Y C. BOLA AMARILLA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP A Y C VISION DE LOS ANDES VISANDES','COOP A Y C VISION DE LOS ANDES VISANDES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SENOR DEL ARBOL','COOP. DE A. Y C. SENOR DEL ARBOL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CAMARA DE COMERCIO DE LA MANA','COOP. DE A. Y C. CAMARA DE COMERCIO DE LA MANA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. EDUCADORES DE LOJA','COOP DE A. Y C. EDUCADORES DE LOJA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. INDIGENA SAC LATACUNGA LTDA','COOP DE A. Y C. INDIGENA SAC LATACUNGA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A.Y C. CADECOG GONZANAMA','COOP DE A.Y C. CADECOG GONZANAMA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC COOPYMEC MACARA','COAC COOPYMEC MACARA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC CADECOM MACARA','COAC CADECOM MACARA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. 22 DE JUNIO-ORIANGA','COOP DE A. Y C. 22 DE JUNIO-ORIANGA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. A.YC.SAGRADA FAMILIA SOLIDARIDAD','COOP. A.YC.SAGRADA FAMILIA SOLIDARIDAD',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. NAUPA KAUSAY','COOP. DE A. Y C. NAUPA KAUSAY',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CCOP A Y C DE APECAP CAC APECAP','CCOP A Y C DE APECAP CAC APECAP',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP DE A. Y C. SAN JUAN DE COTOGCHOA','OOP DE A. Y C. SAN JUAN DE COTOGCHOA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE AHORRO Y CREDITO LA MERCED','COOP DE AHORRO Y CREDITO LA MERCED',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE A. Y C. COOPTOPAXI LTDA.','OOP. DE A. Y C. COOPTOPAXI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE A. Y C. GRAMEEN AMAZONAS','OOP. DE A. Y C. GRAMEEN AMAZONAS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE A. Y C. EL TRANSPORTISTA CACET','OOP. DE A. Y C. EL TRANSPORTISTA CACET',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE A Y C. SERVIDORES MUNICIPALES DE CUENCA','OOP. DE A Y C. SERVIDORES MUNICIPALES DE CUENCA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE AHORRO Y CREDITO PROFUTURO LTDA.','OOP. DE AHORRO Y CREDITO PROFUTURO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE A. Y C. ILINIZA LTDA.','OOP. DE A. Y C. ILINIZA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE AHORRO Y CREDITO SARAGUROS','OOP. DE AHORRO Y CREDITO SARAGUROS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOPERATIVA DE AHORRO Y CREDITO INTI WASI LTDA.','OOPERATIVA DE AHORRO Y CREDITO INTI WASI LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOPERATIVA DE AHORRO Y CREDITO SAN ISIDRO LTDA.','OOPERATIVA DE AHORRO Y CREDITO SAN ISIDRO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE A. Y C. EMPRESAS COMUNITARIAS COOCREDITO','OOP. DE A. Y C. EMPRESAS COMUNITARIAS COOCREDITO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ILVERCROSS S.A CASA DE VALORES SCCV','ILVERCROSS S.A CASA DE VALORES SCCV',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'EAL CASA DE VALORES DE GUAYAQUIL S.A.','EAL CASA DE VALORES DE GUAYAQUIL S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOPERATIVA DE AHORRO Y CREDITO ETAPA','OOPERATIVA DE AHORRO Y CREDITO ETAPA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. AHORRO Y CREDITO MASCOOP','OOP. AHORRO Y CREDITO MASCOOP',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'OOP. DE A. Y C. SAINT MICHEL LTDA.','OOP. DE A. Y C. SAINT MICHEL LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO MANANTIAL DE ORO LTDA.','COOP. AHORRO Y CREDITO MANANTIAL DE ORO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO ANDINA LTDA.','COOP. DE AHORRO Y CREDITO ANDINA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO ACCION Y DESARROLLO LTDA','COOP. DE AHORRO Y CREDITO ACCION Y DESARROLLO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. UNION Y DESARROLLO','COOP. DE A. Y C. UNION Y DESARROLLO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. ESPERANZA DEL FUTURO LTDA.','COOP. DE A. Y C. ESPERANZA DEL FUTURO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 17 DE MARZO LTDA','COOP. DE A. Y C. 17 DE MARZO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CATAR LTDA','COOP. DE A. Y C. CATAR LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. DE ACCION POPULAR','COOP. DE A. Y C. DE ACCION POPULAR',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. ALLI TARPUK LTDA','COOP. DE A. Y C. ALLI TARPUK LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 16 DE JULIO LTDA','COOP. DE A. Y C. 16 DE JULIO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SUBOFICIALES DE LA POLICIA NACION','COOP. DE A. Y C. SUBOFICIALES DE LA POLICIA NACION',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. POLITECNICA LTDA.','COOP. DE A. Y C. POLITECNICA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. NACIONAL LLANO GRANDE LTDA.','COOP. DE A. Y C. NACIONAL LLANO GRANDE LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SAN VALENTIN','COOP. DE A. Y C. SAN VALENTIN',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. TOTALIFE LTDA','COOP. DE A. Y C. TOTALIFE LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ACCIONES VALORES CASA DE VALORES S.A. ACCIVAL','ACCIONES VALORES CASA DE VALORES S.A. ACCIVAL',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'SANTA FE CASA DE VALORES S.A. SANTAFEVALORES','SANTA FE CASA DE VALORES S.A. SANTAFEVALORES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'PICAVAL CASA DE VALORES S.A','PICAVAL CASA DE VALORES S.A',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ANALYTICA SECURTIES C.A. CASA DE VALORES','ANALYTICA SECURTIES C.A. CASA DE VALORES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ORION CASA DE VALORES S.A','ORION CASA DE VALORES S.A',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'STRATEGA CASA DE VALORES S.A.','STRATEGA CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ECOFSA CASA DE VALORES S.A.','ECOFSA CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'MERCHANTVALORES CASA DE VALORES S.A.','MERCHANTVALORES CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CASA DE VALORES VALUE S.A.','CASA DE VALORES VALUE S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'INMOVALOR CASA DE VALORES S.A.','INMOVALOR CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ECUABURSATIL CASA DE VALORES S.A.','ECUABURSATIL CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'PLUS VALORES CASA DE VALORES S.A.','PLUS VALORES CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'MERCAPITAL CASA DE VALORES S.A.','MERCAPITAL CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'PORTAFOLIO CASA DE VALORES S.A. PORTAVALOR','PORTAFOLIO CASA DE VALORES S.A. PORTAVALOR',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'METROVALORES CASA DE VALORES S.A.','METROVALORES CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'VECTORGLOBAL WMG CASA DE VALORES S.A.','VECTORGLOBAL WMG CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'HOLDUNPARTNERS CASA DE VALORES S.A.','HOLDUNPARTNERS CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE AHORRO Y CREDITO BASE DE TAURA','COOP. DE AHORRO Y CREDITO BASE DE TAURA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CASA DE VALORES BANRIO S.A.','CASA DE VALORES BANRIO S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ALBION CASA DE VALORES S.A.','ALBION CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'MASVALORES CASA DE VALORES S.A CAVAMASA','MASVALORES CASA DE VALORES S.A CAVAMASA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CASA DE VALORES DEL PACIFICO (VALPACIFICO) S.A.','CASA DE VALORES DEL PACIFICO (VALPACIFICO) S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CASA DE VALORES ADVFIN S.A.','CASA DE VALORES ADVFIN S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'KAPITAL ONE CASA DE VALORES S.A. KAOVALSA','KAPITAL ONE CASA DE VALORES S.A. KAOVALSA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'PLUSBURSATIL CASA DE VALORES S.A','PLUSBURSATIL CASA DE VALORES S.A',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'ACTIVA ASES.E INTERMED.VALORES ACTIVALORES CASA DE','ACTIVA ASES.E INTERMED.VALORES ACTIVALORES CASA DE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CITADEL CASA DE VALORES S.A.','CITADEL CASA DE VALORES S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'DECEVALE S.A.','DECEVALE S.A.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SANTA LUCIA LTDA','COOP. DE A. Y C. SANTA LUCIA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. PRODUACTIVA LTDA','COOP. DE A. Y C. PRODUACTIVA LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. TAMBOLOMA LTDA.','COOP. DE A. Y C. TAMBOLOMA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP DE A. Y C. PUSHAK RUNA HOMBRE LIDER','COOP DE A. Y C. PUSHAK RUNA HOMBRE LIDER',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 15 DE AGOSTO LTDA.','COOP. DE A. Y C. 15 DE AGOSTO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. MIGRANTES DEL ECUADOR LTDA','COOP. DE A. Y C. MIGRANTES DEL ECUADOR LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOPERATIVA DE AHORRO Y CREDITO WUAMANLOMA LTDA.','COOPERATIVA DE AHORRO Y CREDITO WUAMANLOMA LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SALATE LTDA.','COOP. DE A. Y C. SALATE LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. UNION POPULAR LTDA.','COOP. DE A. Y C. UNION POPULAR LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC ACHIK INTI LTDA','COAC ACHIK INTI LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC EL MIGRANTE SOLIDARIO','COAC EL MIGRANTE SOLIDARIO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP AC LAS NAVES','COOP AC LAS NAVES',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. DE IMBABURA AMAZONAS','COOP. DE A. Y C. DE IMBABURA AMAZONAS',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. A. Y C. DE INDIGENAS CHUCHUQUI LTDA','COOP. A. Y C. DE INDIGENAS CHUCHUQUI LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO FOCAZSUM LTDA.','COOP. AHORRO Y CREDITO FOCAZSUM LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. SOLIDARIA LTDA.- COTOPAXI','COOP. DE A. Y C. SOLIDARIA LTDA.- COTOPAXI',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. UNIDAD Y PROGRESO','COOP. DE A. Y C. UNIDAD Y PROGRESO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC LOJA INTERNACIONAL LTDA.','COAC LOJA INTERNACIONAL LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC 23 DE ENERO','COAC 23 DE ENERO',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC OBRAS PUBLICAS FISCALES DE LOJA Y ZAMORA','COAC OBRAS PUBLICAS FISCALES DE LOJA Y ZAMORA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC DEL SIND CHOF PROF VIRGEN DEL CISNE','COAC DEL SIND CHOF PROF VIRGEN DEL CISNE',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC SAN MIGUEL DE CHIRIJOS LTDA','COAC SAN MIGUEL DE CHIRIJOS LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. AHORRO Y CREDITO QUEVEDO LTDA.','COOP. AHORRO Y CREDITO QUEVEDO LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. EL ALTAR LTDA.','COOP. DE A. Y C. EL ALTAR LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. NUEVA ALIANZA DE CHIMBORAZO LTDA','COOP. DE A. Y C. NUEVA ALIANZA DE CHIMBORAZO LTDA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. LUIS FELIPE DUCHICELA XXVII','COOP. DE A. Y C. LUIS FELIPE DUCHICELA XXVII',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. NIZAG LTDA.','COOP. DE A. Y C. NIZAG LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. MAKITA KUNCHIK','COOP. DE A. Y C. MAKITA KUNCHIK',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. CERRADA MANUELA LEON','COOP. DE A. Y C. CERRADA MANUELA LEON',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. EL BUEN SEMBRADOR LTDA.','COOP. DE A. Y C. EL BUEN SEMBRADOR LTDA.',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COAC SINDICATO DE CHOFERES PROFESIONALES DE YANTZA','COAC SINDICATO DE CHOFERES PROFESIONALES DE YANTZA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'COOP. DE A. Y C. 5 DE MAYO DE SANTA MARTHA DE CUBA','COOP. DE A. Y C. 5 DE MAYO DE SANTA MARTHA DE CUBA',@IdPadre,1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL,'CITIBANK FSB','CITIBANK FSB',@IdPadre,1,1,0)
GO
/*****************************************************/
/***********SPRINT 1: ASIGNACION EQUIPOS**************/
/*****************************************************/

/*****************  Tarea 47  ************************
	Proyecto: RRHH									
	Fecha: 25/feb/2021
	Descripción: Es necesario generar estados que 
		permitan a RRHH ver el estado en el cual se 
		encuentra la compra del equipo, este estado
		debe irlo ingresando Compras (Liz). TRACKING
*****************************************************/
ALTER TABLE RequerimientoEquipo ADD Tracking INT NULL

DECLARE @CatalogoPadre VARCHAR(20) = 'TRACK-01'
DECLARE @IdCatalogoPadre INT

INSERT INTO adm.Catalogo VALUES(@CatalogoPadre, 'TRACKING REQUERIMIENTO','NOMBRE DEL ESTADO DE TRACKING DEL REQUERIMIENTO DE EQUIPOS',NULL,1,1,0)

SELECT @IdCatalogoPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @CatalogoPadre


DECLARE @NombreCatalogo1 VARCHAR(20) = 'SOLICITADO'
INSERT INTO adm.Catalogo VALUES (NULL, @NombreCatalogo1, @NombreCatalogo1, @IdCatalogoPadre, 1,1,0)

DECLARE @NombreCatalogo2 VARCHAR(20) = 'COMPRADO'
INSERT INTO adm.Catalogo VALUES (NULL, @NombreCatalogo2, @NombreCatalogo2, @IdCatalogoPadre, 1,1,0)
GO
ALTER VIEW [dbo].[vwRequerimientoEquipo] AS  
SELECT RE.[IDRequerimientoEquipo]  
      ,RE.[FechaSolicitud]  
      ,RE.[UsuarioID]  
	  ,RE.Tracking
   ,RE.UsuarioSolicitanteID  
   --,'' AS NombresSolicitante  
   ,([adm].NombresCompletosUsuario(RE.UsuarioSolicitanteID)) as NombresSolicitante  
  
  
   ,RE.[Estado] AS EstadoRequerimientoEquipo  
   ,(CASE WHEN RE.[Estado] = 0 THEN 'ELIMINADO' ELSE 'ACTIVO' END) AS TextoEstadoRequerimientoEquipo  
        
      ,(dbo.[ObtenerEquiposByRequerimientoEquipo] (RE.[IDRequerimientoEquipo])) as Equipos     
   ,(dbo.[ObtenerEquiposIDsByRequerimientoEquipo] (RE.[IDRequerimientoEquipo])) as IDsEquipos  
     ,(dbo.[ObtenerProveedorEquiposByRequerimientoEquipo] (RE.[IDRequerimientoEquipo])) as ProveedorEquipos     
   ,(dbo.[ObtenerCostoEquiposByRequerimientoEquipo] (RE.[IDRequerimientoEquipo])) as CostoEquipos  
  
      ,([dbo].[ObtenerHerramientasAdicionalesByRequerimientoEquipo] (RE.[IDRequerimientoEquipo])) as HerramientasAdicionales     
   ,([dbo].[ObtenerHerramientasAdicionalesIDsByRequerimientoEquipo] (RE.[IDRequerimientoEquipo])) as IDsHerramientasAdicionales  
  
  
   --SUGERENCIA DE EQUIPOS  
      ,([dbo].[ObtenerEquipoSugeridosByCargo] (U.[Cargo])) as EquiposSugeridosCargoUsuario    
   ,([dbo].[ObtenerEquipoSugeridosIDsByCargo] (U.[Cargo])) as IDsEquiposSugeridosCargoUsuario   
  
  
   ,RE.FechaEstimadaEntregaEquipos  
  
   ,RE.Asignado  
   ,RE.FechaAsignacion  
    ,I.CredencialAcceso  
   ,(CASE WHEN RE.Asignado = 1 THEN 'ASIGNADO' ELSE 'PENDIENTE' END) AS TextoAsignadoRequerimientoEquipo  
   ,RE.Aprobado  
   ,RE.FechaAprobacion  
   ,(CASE WHEN RE.Aprobado = 1 THEN 'APROBADO'   
       WHEN RE.Aprobado = 0 THEN 'PENDIENTE'  
    ELSE '' END) AS TextoAprobadoRequerimientoEquipo  
   --USUARIO  
      ,U.[Identificacion]  
      ,U.[Nombres]  
      ,U.[Apellidos]  
      ,U.[NombresApellidos]  
      ,U.[Username]  
      ,U.[Area]  
      ,U.[TextoCatalogoArea]  
      ,U.[Departamento]  
      ,U.[TextoCatalogoDepartamento]  
      ,U.[Cargo]  
      ,U.[TextoCatalogoCargo]  
      ,U.[IdEmpresa]  
      ,U.[NombreEmpresa]  
      ,U.[Pais]  
      ,U.[TextoCatalogoPais]  
      ,U.[Ciudad]  
      ,U.[TextoCatalogoCiudad]  
      ,U.[Direccion]  
      ,U.[Mail]  
   ,U.[MailCorporativo]  
     
      ,U.[Clave]  
      ,U.[Telefono]  
      ,U.[Celular]  
      ,U.[IdRol]  
      ,U.[NombreRol]  
      ,U.[DescripcionRol]  
      ,U.[EstadoRol]  
      ,U.[TextoEstadoRol]  
      ,U.[EstadoUsuario]  
      ,U.[TextoEstadoUsuario]  
     ,U.[Activo]  
  --FICHA INGRESO  
  ,FI.[FechaIngreso] --GETDATE() AS FechaIngreso-  
  --Ingreso  
  ,I.[JefeDirecto]  
  ,[adm].[NombreCatalogo](I.JefeDirecto) as TextoCatalogoJefeDirecto  
  ,I.[PersonaReemplazante]  
  ,I.[TipoIngreso]  
  ,[adm].[NombreCatalogo](I.[TipoIngreso]) as TextoCatalogoTipoIngreso  
      ,I.[CorreoAsignado]  
      ,I.[Sueldo]  
   ,I.[TipoContrato]  
   ,[adm].[NombreCatalogo](I.[TipoContrato]) as TextoCatalogoTipoContrato  
   ,I.[GrupoCorreo]  
   ,[adm].[NombreCatalogo](I.GrupoCorreo) as TextoCatalogoGrupoCorreo  
  
   ,CAST((CASE WHEN CODE.IDCodificacionEquipo IS NOT NULL THEN 1 ELSE 0 END) AS BIT) AS TieneCodificacion  
  
  FROM [dbo].[RequerimientoEquipo] RE  
   LEFT JOIN [adm].vwUsuario U ON U.IdUsuario = RE.UsuarioID  
   --LEFT JOIN [dbo].vwFichaIngreso FI ON U.IdUsuario = RE.UsuarioID  
  LEFT JOIN [dbo].vwFichaIngreso FI ON FI.UsuarioID = RE.UsuarioID  
   LEFT JOIN [dbo].Ingreso I ON I.FichaIngresoID = FI.IDFichaIngreso  
  -- PARA VERIFICAR CODIFICACIONES  
  LEFT  JOIN dbo.CodificacionEquipo CODE ON CODE.RequerimientoEquipoID = RE.IDRequerimientoEquipo  
   where  RE.[Estado] = 1  
 GO
/*****************  Tarea 51  ************************
	Proyecto: RRHH									
	Fecha: 25/feb/2021
	Descripción: Agregar en campo tipo de contrato
	"Servicios Prestados"
*****************************************************/
 DECLARE @IdPadre INT
SELECT @IdPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = 'TIPO-CONTR-01'
INSERT INTO adm.Catalogo VALUES (NULL, 'SERVICIOS PRESTADOS','SERVICIOS PRESTADOS', @IdPadre,1,1,0)
GO
/*****************  Tarea 53  ************************
	Proyecto: RRHH									
	Fecha: 02/mar/2021
	Descripción: Agregar permisos y catalogos en 
	base de datos para nuevo modulo, crear SP
*****************************************************/
DECLARE @NombreMenu VARCHAR(50) = 'NUEVO'
DECLARE @MenuPadre INT 
DECLARE @OrdenMenu INT

SELECT @MenuPadre = IdMenu FROM adm.Menu WHERE NombreMenu = 'Gestión'
SELECT @OrdenMenu = MAX(OrdenMenu)+1 FROM adm.Menu

INSERT INTO adm.Menu VALUES ('Modificación de Equipos', 'ModificacionEquipo/Index', 1, @MenuPadre, @OrdenMenu)

GO

DECLARE @CodigoCatalogoPadre VARCHAR(50) = 'ACCIONES-SIST-01'
DECLARE @CodigoNuevoCatalogo VARCHAR(50) = 'ACCIONES-SIST-MOD-EQUIPOS'
DECLARE @Rol VARCHAR(50) = 'ADMINISTRADOR DEL SISTEMA'
DECLARE @Perfil VARCHAR(50) = 'ADMINISTRADOR'
DECLARE @Menu VARCHAR(50)= 'Modificación de Equipos'
DECLARE @IdRol INT, @IdPerfil INT, @IdMenu INT,@IdPadre INT
DECLARE @Catalogos TABLE (ID INT)

SELECT @IdPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @CodigoCatalogoPadre

INSERT INTO @Catalogos
SELECT IdCatalogo FROM adm.Catalogo 
WHERE IdCatalogoPadre = @IdPadre AND 
CodigoCatalogo IN ('ACCIONES-SIST-BUSQUEDA','ACCIONES-SIST-ACTUALIZAR','ACCIONES-SIST-DESCARGAR','ACCIONES-SIST-REPORTES-BASICOS')


SELECT @IdRol = IdRol FROM adm.Rol WHERE Nombre = @Rol
SELECT @IdPerfil = IdPerfil FROM adm.Perfil WHERE NombrePerfil = @Perfil
SELECT @IdMenu = IdMenu FROM adm.Menu WHERE NombreMenu = @Menu

INSERT INTO adm.RolMenuPermiso 
SELECT @IdRol, @IdPerfil, @IdMenu, Id, 1, 1, GETDATE(), GETDATE(), 1 
FROM @Catalogos

INSERT INTO adm.PerfilMenu
VALUES (@IdPerfil, @IdMenu)

GO
-- CREACION CATALOGOS ESTADO ASIGNACION
ALTER TABLE RequerimientoEquipoUsuario ADD Estado INT
ALTER TABLE RequerimientoEquipoHerramientasAdicionales ADD Estado INT
ALTER TABLE RequerimientoEquipoUsuario ADD FechaModificacion DATETIME
ALTER TABLE RequerimientoEquipoHerramientasAdicionales ADD FechaModificacion DATETIME
ALTER TABLE RequerimientoEquipoHerramientasAdicionales ADD Observaciones VARCHAR(100)
ALTER TABLE RequerimientoEquipoUsuario ADD Observaciones VARCHAR(100)


DECLARE @CodigoCatalogoPadre VARCHAR(50) = 'ESTADO-ASIGNACION-EQUIPOS'
DECLARE @CodigoNuevoCatalogo1 VARCHAR(50) = 'ASIGNADO'
DECLARE @CodigoNuevoCatalogo2 VARCHAR(50) = 'DEVUELTO'
DECLARE @IdPadre INT 

INSERT INTO adm.Catalogo VALUES (@CodigoCatalogoPadre, 'ESTADOS DE ASINGACION DE EQUIPOS', 'ESTADO DE EQUIPO ASIGNADO UNA VEZ SE HA APROBADO SU REQUERIMIENTO',NULL,1,1,0)
SELECT @IdPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @CodigoCatalogoPadre

INSERT INTO adm.Catalogo VALUES (NULL, @CodigoNuevoCatalogo1, @CodigoNuevoCatalogo1, @IdPadre, 1,1,0)
INSERT INTO adm.Catalogo VALUES (NULL, @CodigoNuevoCatalogo2, @CodigoNuevoCatalogo2, @IdPadre, 1,1,0)
GO
/*******************************************/
/* Procedimiento para obtener equipos y 
herramientas adicionales para el usuario dado
********************************************/
CREATE PROCEDURE ListadoEquiposAsignadosUsuario
@IdUsuario INT
AS
IF @IdUsuario IS NULL
BEGIN
	SELECT  
		re.IDRequerimientoEquipo,	
		CONCAT(u.Nombres,' ',u.Apellidos) AS NombresApellidos,
		e.Nombre AS Equipo,
		'Equipo' AS TipoEquipo,
		e.IDEquipo,
		reu.IDRequerimientoEquipoUsuario,
		reu.Estado,
		c.NombreCatalogo,
		reu.FechaModificacion,
		reu.Observaciones
	FROM RequerimientoEquipo re
	JOIN adm.Usuario u ON re.UsuarioID = u.IdUsuario
	JOIN RequerimientoEquipoUsuario reu ON re.IDRequerimientoEquipo = reu.RequerimientoEquipoID
	JOIN Equipo e ON e.IDEquipo = reu.EquipoID
	LEFT JOIN adm.Catalogo c ON reu.Estado = c.IdCatalogo
	WHERE re.FechaAsignacion IS NOT NULL AND re.Asignado = 1
	UNION ALL
	SELECT
		rh.IDRequerimientoEquipo,
		rh.NombresApellidos,
		rh.TextoCatalogoHerramientaAdicional,
		'Herramienta Adicional' AS TipoEquipo,
		rha.HerramientaAdicional,
		rha.IDRequerimientoEquipoHerramientasAdicionales,
		rha.Estado,
		c.NombreCatalogo,
		rha.FechaModificacion,
		rha.Observaciones
	FROM vwRequerimientoEquipoHerramientasAdicionales rh
	JOIN RequerimientoEquipoUsuario reu ON rh.IDRequerimientoEquipo = reu.RequerimientoEquipoID
	JOIN RequerimientoEquipoHerramientasAdicionales rha ON rh.IDRequerimientoEquipo = rha.RequerimientoEquipoID
	JOIN Equipo e ON reu.EquipoID = e.IDEquipo
	LEFT JOIN adm.Catalogo c ON rha.Estado = c.IdCatalogo
	WHERE 
	e.IDEquipo IN (
	SELECT MIN(e.IDEquipo) FROM vwRequerimientoEquipoHerramientasAdicionales rh
	JOIN RequerimientoEquipoUsuario reu ON rh.IDRequerimientoEquipo = reu.RequerimientoEquipoID
	JOIN Equipo e ON reu.EquipoID = e.IDEquipo)
END
ELSE 
BEGIN
	SELECT  
		re.IDRequerimientoEquipo,	
		CONCAT(u.Nombres,' ',u.Apellidos) AS NombresApellidos,
		e.Nombre AS Equipo,
		'Equipo' AS TipoEquipo,
		e.IDEquipo,
		reu.IDRequerimientoEquipoUsuario,
		reu.Estado,
		c.NombreCatalogo,
		reu.FechaModificacion,
		reu.Observaciones
	FROM RequerimientoEquipo re
	JOIN adm.Usuario u ON re.UsuarioID = u.IdUsuario
	JOIN RequerimientoEquipoUsuario reu ON re.IDRequerimientoEquipo = reu.RequerimientoEquipoID
	JOIN Equipo e ON e.IDEquipo = reu.EquipoID
	LEFT JOIN adm.Catalogo c ON reu.Estado = c.IdCatalogo
	WHERE re.FechaAsignacion IS NOT NULL AND u.IdUsuario = @IdUsuario AND re.Asignado = 1
	UNION ALL
	SELECT
		rh.IDRequerimientoEquipo,
		rh.NombresApellidos,
		rh.TextoCatalogoHerramientaAdicional,
		'Herramienta Adicional' AS TipoEquipo,
		rha.HerramientaAdicional,
		rha.IDRequerimientoEquipoHerramientasAdicionales,
		rha.Estado,
		c.NombreCatalogo,
		rha.FechaModificacion,
		rha.Observaciones
	FROM vwRequerimientoEquipoHerramientasAdicionales rh
	JOIN RequerimientoEquipoUsuario reu ON rh.IDRequerimientoEquipo = reu.RequerimientoEquipoID
	JOIN RequerimientoEquipoHerramientasAdicionales rha ON rh.IDRequerimientoEquipo = rha.RequerimientoEquipoID
	JOIN Equipo e ON rha.HerramientaAdicional = e.IDEquipo
	LEFT JOIN adm.Catalogo c ON rha.Estado = c.IdCatalogo
	WHERE rh.UsuarioID = @IdUsuario AND
	e.IDEquipo IN (
	SELECT MIN(e.IDEquipo) FROM vwRequerimientoEquipoHerramientasAdicionales rh
	JOIN RequerimientoEquipoHerramientasAdicionales reu ON rh.IDRequerimientoEquipo = reu.RequerimientoEquipoID
	JOIN RequerimientoEquipo re ON re.IDRequerimientoEquipo = reu.RequerimientoEquipoID
	JOIN Equipo e ON rh.HerramientaAdicional = e.IDEquipo
	WHERE rh.UsuarioID = @IdUsuario)
END
GO
/*****************  Tarea 59  ************************
	Proyecto: RRHH									
	Fecha: 04/mar/2021
	Descripción:  Implementar envio correo pruebas
*****************************************************/
DECLARE @IdPadre INT
DECLARE @CatalogoNuevo VARCHAR(50) = 'CORREOS-PRUEBAS'
INSERT INTO adm.Catalogo VALUES (@CatalogoNuevo, 'CORREOS PRUEBAS PARA APLICACIONES', 'CORREOS PARA EJECUCION DE PRUEBAS DE APLICACION', NULL,1,1,0)
SELECT @IdPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @CatalogoNuevo
INSERT INTO adm.Catalogo VALUES (NULL, 'RRHH', 'esteban.morejon@qph.com.ec; carlos.totoy@qph.com.ec', @IdPadre,1,1,0)
GO

/*****************  Tarea 59  ************************
	Proyecto: RRHH									
	Fecha: 05/mar/2021
	Descripción:  Asignacion de equipos incluye campo
	asignacion y fecha
*****************************************************/
CREATE PROCEDURE AsignarEquiposPorRequerimiento @IdRequerimientoEquipo INT
AS
DECLARE @CodigoCatalogoPadre VARCHAR(50) = 'ESTADO-ASIGNACION-EQUIPOS'
DECLARE @CodigoAsignado VARCHAR(50) = 'ASIGNADO'
DECLARE @IdPadre INT
DECLARE @IdEstado INT 

SELECT @IdPadre = IdCatalogo FROM adm.Catalogo WHERE CodigoCatalogo = @CodigoCatalogoPadre
SELECT @IdEstado = IdCatalogo FROM adm.Catalogo WHERE NombreCatalogo = @CodigoAsignado AND IdCatalogoPadre = @IdPadre

UPDATE RequerimientoEquipoUsuario SET Estado = @IdEstado, FechaModificacion = GETDATE() 
WHERE RequerimientoEquipoID = @IdRequerimientoEquipo

UPDATE RequerimientoEquipoHerramientasAdicionales SET Estado = @IdEstado, FechaModificacion = GETDATE() 
WHERE RequerimientoEquipoID = @IdRequerimientoEquipo